/*
 * InterServer Management API
 *
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * API version: 0.9.0
 * Contact: support@interserver.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package myadmin-client-go-server

// Request body to place a custom dedicated server order. All ids come from getNewServer's config_li / regions.
type ServerOrderPostRequest struct {
	// CPU configuration id from config_li.cpu_li. Constrains valid hd/memory options.
	Cpu int32 `json:"cpu"`
	// Hard-drive configuration id(s) from config_li.hd_li[cpu]. Accepts a single id or an array of ids.
	Hd *OneOfServerOrderPostRequestHd `json:"hd"`
	// Memory configuration id from config_li.memory_li[cpu].
	Memory int32 `json:"memory"`
	// Bandwidth configuration id from config_li.bandwidth_li.
	Bandwidth int32 `json:"bandwidth"`
	// IP block configuration id from config_li.ips_li.
	Ips int32 `json:"ips"`
	// Operating System configuration id from config_li.os_li.
	Os int32 `json:"os"`
	// Control Panel configuration id from config_li.cp_li.
	Cp int32 `json:"cp"`
	// RAID configuration id from config_li.raid_li.
	Raid int32 `json:"raid"`
	// Region id from the regions list.
	Region int32 `json:"region"`
	// Server hostname. Must pass valid_hostname().
	Servername string `json:"servername"`
	// Root password for the server.
	Rootpass string `json:"rootpass"`
	// Terms-of-service acceptance. Must be true to place the order.
	Tos bool `json:"tos"`
	// Optional free-form order comment.
	Comment string `json:"comment,omitempty"`
}
