//
// ServerOrderRAID.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A RAID configuration option available when ordering a dedicated server. */
@objcMembers public final class ServerOrderRAID: NSObject, Codable, @unchecked Sendable {

    /** RAID ID. */
    public private(set) var _id: String?
    /** RAID price. */
    public private(set) var price: Int?
    public var priceNum: NSNumber? {
        get {
            return price as NSNumber?
        }
    }
    /** RAID image. */
    public private(set) var img: String?
    /** Short description of the RAID. */
    public private(set) var shortDesc: String?
    /** Long description of the RAID. */
    public private(set) var longDesc: String?
    /** Monthly price. */
    public private(set) var monthlyPrice: Int?
    public var monthlyPriceNum: NSNumber? {
        get {
            return monthlyPrice as NSNumber?
        }
    }
    /** Active status. */
    public private(set) var active: String?
    /** Display of RAID price. */
    public private(set) var priceDisplay: String?
    /** Display of monthly RAID price. */
    public private(set) var monthlyPriceDisplay: String?

    public init(_id: String? = nil, price: Int? = nil, img: String? = nil, shortDesc: String? = nil, longDesc: String? = nil, monthlyPrice: Int? = nil, active: String? = nil, priceDisplay: String? = nil, monthlyPriceDisplay: String? = nil) {
        self._id = _id
        self.price = price
        self.img = img
        self.shortDesc = shortDesc
        self.longDesc = longDesc
        self.monthlyPrice = monthlyPrice
        self.active = active
        self.priceDisplay = priceDisplay
        self.monthlyPriceDisplay = monthlyPriceDisplay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case price
        case img
        case shortDesc = "short_desc"
        case longDesc = "long_desc"
        case monthlyPrice = "monthly_price"
        case active
        case priceDisplay = "price_display"
        case monthlyPriceDisplay = "monthly_price_display"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(img, forKey: .img)
        try container.encodeIfPresent(shortDesc, forKey: .shortDesc)
        try container.encodeIfPresent(longDesc, forKey: .longDesc)
        try container.encodeIfPresent(monthlyPrice, forKey: .monthlyPrice)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encodeIfPresent(priceDisplay, forKey: .priceDisplay)
        try container.encodeIfPresent(monthlyPriceDisplay, forKey: .monthlyPriceDisplay)
    }
}


extension ServerOrderRAID: Identifiable {}
