//
// TicketCustomFieldDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Optional fields providing additional info in ticket */
@objcMembers public final class TicketCustomFieldDetails: NSObject, Codable, @unchecked Sendable {

    public enum CustomerServerAccess: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case y = "y"
        case n = "n"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public private(set) var customerServerAccess: CustomerServerAccess?
    public private(set) var ipAddress: String?
    public private(set) var rootPassword: String?
    public private(set) var sudoUser: String?
    public private(set) var sudoPassword: Int?
    public var sudoPasswordNum: NSNumber? {
        get {
            return sudoPassword as NSNumber?
        }
    }
    public private(set) var port: Int?
    public var portNum: NSNumber? {
        get {
            return port as NSNumber?
        }
    }

    public init(customerServerAccess: CustomerServerAccess? = nil, ipAddress: String? = nil, rootPassword: String? = nil, sudoUser: String? = nil, sudoPassword: Int? = nil, port: Int? = nil) {
        self.customerServerAccess = customerServerAccess
        self.ipAddress = ipAddress
        self.rootPassword = rootPassword
        self.sudoUser = sudoUser
        self.sudoPassword = sudoPassword
        self.port = port
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerServerAccess = "Customer Server Access"
        case ipAddress = "Ip Address"
        case rootPassword = "Root Password"
        case sudoUser = "Sudo User"
        case sudoPassword = "Sudo Password"
        case port = "Port"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customerServerAccess, forKey: .customerServerAccess)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(rootPassword, forKey: .rootPassword)
        try container.encodeIfPresent(sudoUser, forKey: .sudoUser)
        try container.encodeIfPresent(sudoPassword, forKey: .sudoPassword)
        try container.encodeIfPresent(port, forKey: .port)
    }
}


extension TicketCustomFieldDetails: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if customerServerAccess == .unknownDefaultOpenApi { return true }
        return false
    }
}
