//
// VpsOrderOsNames.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OS Names */
@objcMembers public final class VpsOrderOsNames: NSObject, Codable, @unchecked Sendable {

    public private(set) var opensuse: String?
    public private(set) var ubuntu: String?

    public init(opensuse: String? = nil, ubuntu: String? = nil) {
        self.opensuse = opensuse
        self.ubuntu = ubuntu
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case opensuse
        case ubuntu
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(opensuse, forKey: .opensuse)
        try container.encodeIfPresent(ubuntu, forKey: .ubuntu)
    }
}

