//
// VpsServiceMaster.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Information about the host node (hypervisor) running this VPS, including hardware specs and resource utilization. */
@objcMembers public final class VpsServiceMaster: NSObject, Codable, @unchecked Sendable {

    /** VPS ID */
    public private(set) var vpsId: String?
    /** VPS name */
    public private(set) var vpsName: String?
    /** IP address of the VPS */
    public private(set) var vpsIp: String?
    /** VPS type */
    public private(set) var vpsType: String?
    /** Hard drive size */
    public private(set) var vpsHdsize: String?
    /** Free hard drive space */
    public private(set) var vpsHdfree: String?
    /** Bits */
    public private(set) var vpsBits: String?
    /** CPU load */
    public private(set) var vpsLoad: String?
    /** RAM */
    public private(set) var vpsRam: String?
    /** CPU model */
    public private(set) var vpsCpuModel: String?
    /** CPU frequency in MHz */
    public private(set) var vpsCpuMhz: String?
    /** Location of the VPS */
    public private(set) var vpsLocation: String?
    /** Last update date */
    public private(set) var vpsLastUpdate: String?
    /** RAID building status */
    public private(set) var vpsRaidBuilding: String?
    /** Kernel version */
    public private(set) var vpsKernel: String?
    /** Available */
    public private(set) var vpsAvailable: String?
    /** Number of CPU cores */
    public private(set) var vpsCores: String?
    /** I/O wait */
    public private(set) var vpsIowait: String?
    /** RAID status */
    public private(set) var vpsRaidStatus: String?
    /** Mounts */
    public private(set) var vpsMounts: String?
    /** Maximum number of servers */
    public private(set) var vpsServerMax: String?
    /** Maximum number of server slices */
    public private(set) var vpsServerMaxSlices: String?
    /** Drive type */
    public private(set) var vpsDriveType: String?
    /** Order number */
    public private(set) var vpsOrder: String?

    public init(vpsId: String? = nil, vpsName: String? = nil, vpsIp: String? = nil, vpsType: String? = nil, vpsHdsize: String? = nil, vpsHdfree: String? = nil, vpsBits: String? = nil, vpsLoad: String? = nil, vpsRam: String? = nil, vpsCpuModel: String? = nil, vpsCpuMhz: String? = nil, vpsLocation: String? = nil, vpsLastUpdate: String? = nil, vpsRaidBuilding: String? = nil, vpsKernel: String? = nil, vpsAvailable: String? = nil, vpsCores: String? = nil, vpsIowait: String? = nil, vpsRaidStatus: String? = nil, vpsMounts: String? = nil, vpsServerMax: String? = nil, vpsServerMaxSlices: String? = nil, vpsDriveType: String? = nil, vpsOrder: String? = nil) {
        self.vpsId = vpsId
        self.vpsName = vpsName
        self.vpsIp = vpsIp
        self.vpsType = vpsType
        self.vpsHdsize = vpsHdsize
        self.vpsHdfree = vpsHdfree
        self.vpsBits = vpsBits
        self.vpsLoad = vpsLoad
        self.vpsRam = vpsRam
        self.vpsCpuModel = vpsCpuModel
        self.vpsCpuMhz = vpsCpuMhz
        self.vpsLocation = vpsLocation
        self.vpsLastUpdate = vpsLastUpdate
        self.vpsRaidBuilding = vpsRaidBuilding
        self.vpsKernel = vpsKernel
        self.vpsAvailable = vpsAvailable
        self.vpsCores = vpsCores
        self.vpsIowait = vpsIowait
        self.vpsRaidStatus = vpsRaidStatus
        self.vpsMounts = vpsMounts
        self.vpsServerMax = vpsServerMax
        self.vpsServerMaxSlices = vpsServerMaxSlices
        self.vpsDriveType = vpsDriveType
        self.vpsOrder = vpsOrder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vpsId = "vps_id"
        case vpsName = "vps_name"
        case vpsIp = "vps_ip"
        case vpsType = "vps_type"
        case vpsHdsize = "vps_hdsize"
        case vpsHdfree = "vps_hdfree"
        case vpsBits = "vps_bits"
        case vpsLoad = "vps_load"
        case vpsRam = "vps_ram"
        case vpsCpuModel = "vps_cpu_model"
        case vpsCpuMhz = "vps_cpu_mhz"
        case vpsLocation = "vps_location"
        case vpsLastUpdate = "vps_last_update"
        case vpsRaidBuilding = "vps_raid_building"
        case vpsKernel = "vps_kernel"
        case vpsAvailable = "vps_available"
        case vpsCores = "vps_cores"
        case vpsIowait = "vps_iowait"
        case vpsRaidStatus = "vps_raid_status"
        case vpsMounts = "vps_mounts"
        case vpsServerMax = "vps_server_max"
        case vpsServerMaxSlices = "vps_server_max_slices"
        case vpsDriveType = "vps_drive_type"
        case vpsOrder = "vps_order"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(vpsId, forKey: .vpsId)
        try container.encodeIfPresent(vpsName, forKey: .vpsName)
        try container.encodeIfPresent(vpsIp, forKey: .vpsIp)
        try container.encodeIfPresent(vpsType, forKey: .vpsType)
        try container.encodeIfPresent(vpsHdsize, forKey: .vpsHdsize)
        try container.encodeIfPresent(vpsHdfree, forKey: .vpsHdfree)
        try container.encodeIfPresent(vpsBits, forKey: .vpsBits)
        try container.encodeIfPresent(vpsLoad, forKey: .vpsLoad)
        try container.encodeIfPresent(vpsRam, forKey: .vpsRam)
        try container.encodeIfPresent(vpsCpuModel, forKey: .vpsCpuModel)
        try container.encodeIfPresent(vpsCpuMhz, forKey: .vpsCpuMhz)
        try container.encodeIfPresent(vpsLocation, forKey: .vpsLocation)
        try container.encodeIfPresent(vpsLastUpdate, forKey: .vpsLastUpdate)
        try container.encodeIfPresent(vpsRaidBuilding, forKey: .vpsRaidBuilding)
        try container.encodeIfPresent(vpsKernel, forKey: .vpsKernel)
        try container.encodeIfPresent(vpsAvailable, forKey: .vpsAvailable)
        try container.encodeIfPresent(vpsCores, forKey: .vpsCores)
        try container.encodeIfPresent(vpsIowait, forKey: .vpsIowait)
        try container.encodeIfPresent(vpsRaidStatus, forKey: .vpsRaidStatus)
        try container.encodeIfPresent(vpsMounts, forKey: .vpsMounts)
        try container.encodeIfPresent(vpsServerMax, forKey: .vpsServerMax)
        try container.encodeIfPresent(vpsServerMaxSlices, forKey: .vpsServerMaxSlices)
        try container.encodeIfPresent(vpsDriveType, forKey: .vpsDriveType)
        try container.encodeIfPresent(vpsOrder, forKey: .vpsOrder)
    }
}

