# #InterServer Management API
#
#The version of the OpenAPI document: 0.9.0
#Contact: support@interserver.net
#Generated by: https://openapi-generator.tech
#Generator version: 7.24.0
#

module InterserverApiClient
  class AccountInfoLimitsInner
    include JSON::Serializable
    include YAML::Serializable
    include InterserverApiClient::Serializable
    include InterserverApiClient::Validation

    # Optional properties
    @[JSON::Field(key: "start", emit_null: false)]
    property start : String?

    @[JSON::Field(key: "end", emit_null: false)]
    property _end : String?


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@start : String? = nil, @_end : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(start, _end)
  end

end
