# #InterServer Management API
#
#The version of the OpenAPI document: 0.9.0
#Contact: support@interserver.net
#Generated by: https://openapi-generator.tech
#Generator version: 7.24.0
#

module InterserverApiClient
  # Request data for a new DNS record.
  class DnsNewRecord
    include JSON::Serializable
    include YAML::Serializable
    include InterserverApiClient::Serializable
    include InterserverApiClient::Validation

    # Required properties
    # Name part of record
    @[JSON::Field(key: "name", emit_null: false)]
    property name : String

    @[JSON::Field(key: "type", emit_null: false)]
    property _type : DnsRecordType

    # Content of record
    @[JSON::Field(key: "content", emit_null: false)]
    property content : String

    # Optional properties
    # Time-to-live
    @[JSON::Field(key: "ttl", emit_null: false)]
    property ttl : Int32? = 86400

    # Priority
    @[JSON::Field(key: "prio", emit_null: false)]
    property prio : Int32? = 0


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@name : String, @_type : DnsRecordType, @content : String, @ttl : Int32? = 86400, @prio : Int32? = 0)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(name, _type, content, ttl, prio)
  end

end
