# #InterServer Management API
#
#The version of the OpenAPI document: 0.9.0
#Contact: support@interserver.net
#Generated by: https://openapi-generator.tech
#Generator version: 7.24.0
#

module InterserverApiClient
  # A mail order record
  class MailOrder
    include JSON::Serializable
    include YAML::Serializable
    include InterserverApiClient::Serializable
    include InterserverApiClient::Validation

    # Required properties
    # The ID of the order.
    @[JSON::Field(key: "id", emit_null: false)]
    property id : Int32

    # The order status.
    @[JSON::Field(key: "status", emit_null: false)]
    property status : String

    # The username to use for this order.
    @[JSON::Field(key: "username", emit_null: false)]
    property username : String

    # Optional properties
    # Optional order comment.
    @[JSON::Field(key: "comment", emit_null: false)]
    property comment : String?


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : Int32, @status : String, @username : String, @comment : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, status, username, comment)
  end

end
