# #InterServer Management API
#
#The version of the OpenAPI document: 0.9.0
#Contact: support@interserver.net
#Generated by: https://openapi-generator.tech
#Generator version: 7.24.0
#

module InterserverApiClient
  # Information about the IPMI connection.
  class ServerIpmiLiveInfo
    include JSON::Serializable
    include YAML::Serializable
    include InterserverApiClient::Serializable
    include InterserverApiClient::Validation

    # Optional properties
    @[JSON::Field(key: "text", emit_null: false)]
    property text : String?

    @[JSON::Field(key: "public_ip", emit_null: false)]
    property public_ip : String?

    @[JSON::Field(key: "allowed_ip", emit_null: false)]
    property allowed_ip : String?

    @[JSON::Field(key: "client_username", emit_null: false)]
    property client_username : String?

    @[JSON::Field(key: "client_password", emit_null: false)]
    property client_password : String?


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@text : String? = nil, @public_ip : String? = nil, @allowed_ip : String? = nil, @client_username : String? = nil, @client_password : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(text, public_ip, allowed_ip, client_username, client_password)
  end

end
