/*
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.interserver.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        builder.disableHtmlEscaping();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountFeatures.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoCountryCurrencies.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoDataCc.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoDataCcs.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoDataEmailSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoDataExtra.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoDataFraudrecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoLimits.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoLimitsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoMaxMindResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoMaxMindResponseRiskScore.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoOauthConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoOauthConfigProviders.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoOauthConfigProvidersValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoOauthproviders.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountInfoPost.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AccountSshKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AddServer200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AffiliateBannerRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AffiliateDockSetup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AffiliatePaymentSetup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.AffiliateTrafficRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Backup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupIPInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupIPInfoRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupLoginResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupOrderPostResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupOrderPostResponseCjParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupOrderPutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupOrderPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupServiceMaster.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupsOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupsOrderPackageCosts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BackupsOrderServiceTypes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingAddCcRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingInvoiceDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingInvoiceList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingPaymentMethodRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingPrepayRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BillingVerifyCcRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowRowCpuInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowRowCpuInnerOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200ResponseBandwidthInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200ResponseCpInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200ResponseIpsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200ResponseOsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.BuyItNowServerOrder200ResponseRaidInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CancelBackup200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CancelDomain200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CancelScrubIp200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CaptchaResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ChargeInvoiceRows.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ChargeInvoiceRowsInvoicesValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ChargeInvoiceRowsInvoicesValuePaidInvoicesValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ChargeInvoiceRowsInvoicesValuePaidInvoicesValueRefundInvoicesValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CloseTicketResponseSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateFilter201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateFilter400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateFilter500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateFirewallRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateGeoFirewallRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateGeoRule400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateRule201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateRule400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.CreateRule500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteFilter200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteFilter400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteFilter500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteFirewallRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteGeoFirewallRule.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DeleteMailAlertRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DenyRuleNew.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DenyRuleRecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DisableScrub200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DisableScrub400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DisableScrub500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DnsListItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DnsNewDomain.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DnsNewRecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DnsRecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DnsUpdateRecord.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Domain.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainAdminContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainAllInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainAllInfoAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainAllInfoAttributesContactSet.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainBillingExtra.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainContactDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainDnssecRecords.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainDnssecRecordsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainDnssecRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainLookupResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainNameServer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainNameserverGetResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainNameserverGetResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainNameserverPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainNameserverPutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrderResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrderResponseAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrderServices.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOrderServices10001.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainOwnerContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainProvProcessPending.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainProvProcessPendingAttributes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainSearchResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainServiceType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainTechContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DomainWhoisPrivacyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DownloadQsBackup200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.DownloadQsBackupRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.EmailAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.EmailAddressName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.EnableScrub200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.EnableScrub500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.FloatingIpOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.FloatingIpsCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GenericResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetAccountInfo401Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetAccountLocales200ResponseValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetAccountTfaSetup200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetAffiliateSignups200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetOauthRedirect200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetOrderDetail200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetOrderDetail200ResponseIpsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetOrderDetail200ResponsePackageCosts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetOrderDetail200ResponseServiceTypesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseClientLinksInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseExtraInfoTablesScrubIps.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseExtraInfoTablesScrubIpsRowsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseFilterFirewall.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseFilterFirewallFiltersInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseFilterFirewallRulesInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetScrubIpDetails200ResponseServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.GetWebsiteBuyIp200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Home.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesBackups.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesDomains.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesLicenses.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesQuickservers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesServers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesVps.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeDetailsModulesWebhosting.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServices.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesBackups.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesDomains.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesDomainsLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesLicenses.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesLicensesLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesServers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesServersLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesVps.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesVpsLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesWebhosting.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeServicesWebhostingLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeTicketStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HomeTicketStatusView.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.HostnameObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.InitiatePayment200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.IpLimitRange.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.IpObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.License.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseIpInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseIpInfoRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicenseServiceType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrderPackageCosts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrderServiceCategories.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrderServiceCategories509.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrderServiceTypes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LicensesOrderServiceTypes11482.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginErrorResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginServiceCounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginSubmissionExample.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginSubmissionExampleGRecaptchaResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginSubmissionExampleGRecaptchaResponseDep.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.LoginSuccessResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailAlertRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailAlertUpdateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailAlertsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailAlertsResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailAttachment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailBlockClickHouse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailBlockRspamd.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailBlocks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailDelistRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailDelistResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailDeliverabilityResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailExtraInfoTable.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailExtraInfoTableRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailLog.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailLogEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailSchemaExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailServiceType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailStatsType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailStatsTypeVolume.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailStatsTypeVolumeFrom.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailStatsTypeVolumeIp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailStatsTypeVolumeTo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailTutorialsTable.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MailTutorialsTableRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ModuleSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Modules.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.MonthlyCounts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PasswordRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PatchBillingCreditCardVerifyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PatchOauthTwoFactor200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PatchOauthTwoFactorRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PlaceBuyNowServerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PlaceScrubOrder201Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PlaceScrubOrder201ResponseOrderDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PlaceScrubOrder201ResponseOrderDetailsCjParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostOauthCallback200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostOauthCallbackRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostWebsiteBuyIp200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostWebsiteBuyIpRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostWebsiteMigration200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PostWebsiteMigrationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.PutScrubIps200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QsOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QueueResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Quickserver.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverAddons.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverAddonsRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverIpInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverIpTableRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderDistroSel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderDistroSelUbuntu.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderServerDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderServerDetails381.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderTemplates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderTemplatesUbuntu64.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderVersion.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverOrderVersionCentosstream8.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverServiceExtra.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserverServiceMaster.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.QuickserversCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ReplyTicketRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ReplyTicketResponseSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.RestoreRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ReverseDnsEntries.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpFilterTypes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpFilterTypesFiltersValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpPlaceOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpsDeleteRule200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpsDeleteRule400Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpsDeleteRule500Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpsLogRowSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ScrubIpsRowSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SearchAutocompleteResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SendMail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SendMailAdv.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Server.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerAsset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerAssets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerBulkIpmiPowerResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerBulkIpmiPowerResponseResultsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerIpmiLiveInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerIpmiLiveRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerIpmiPowerRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerLease.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerLocation1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerLocations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerNetworkInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerNetworkInfoAssets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerNetworkInfoSwitchports.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderBandwidth.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderBandwidthLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderCPU.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderConfigIds.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderControlPanel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderCpLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderCpuLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderFieldLabel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderFieldLabels.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderFormValues.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderIP.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderIpsLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderMemory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderMemoryLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderMemoryLi254.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderOS.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderOsLi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderPostRequestHd.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerOrderRAID.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServerSwitchport.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServersBuyNowError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServersBuyNowResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServersBuyNowResponseOrderDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServersCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Service.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServiceCategories.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServiceCategory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServiceOrderPostResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServiceType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServiceTypes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Services.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ServicesInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SslCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SslOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.StatusMonthlyBreakdown.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.SuccessTextResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TemplateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TextResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketCustomFieldDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketNew.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketNewResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketPostDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketPostDetailsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Tickets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketsCountArray.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TicketsRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.TimezoneUpdate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.UpdateAccountTfaRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.UpdateTicket.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.UpdateTicketResponseSchema.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.UrlRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VPSCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VPSTrafficDataDataSectionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VPSTrafficDataDataSectionResponseInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ViewMailLogStartDateParameter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.ViewTicketResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Vps.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsBackupRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsBackupRows.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsCPData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsDAData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsDALicense.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsIPInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsIPInfoRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderLocationNames.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderLocationStock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderLocationStock1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderOsNames.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPackageCosts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPlatformNames.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPlatformPackages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderServiceTypes.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderServiceTypes32.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderTemplates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderTemplatesHyperv.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsOrderTemplatesHypervWindows.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsPlesk12Data.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsPleskLicense.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsServiceAddons.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsServiceExtra.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsServiceMaster.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsSnapshot.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTemplateRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTemplatesList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficDataSectionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficHistoryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficHistorySectionDataResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficHistorySectionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficTotalsResposne.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficTotalsSectionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficUsageAverageResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficUsageAverageSectionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.VpsTrafficUsageResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebhostingCancel200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.Website.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteBackups.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteBackupsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteBillingDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteClientLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteExtraInfoTables.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteLoginResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteOrderPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteOrderPutRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteServiceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteServiceMaster.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteTable.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsiteTableRow.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderJsonServiceOffers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderJsonServiceOffersItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderJsonServices.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderPackages.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderPackagesInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderPackges.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderServiceOffer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderServiceOffers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.interserver.client.model.WebsitesOrderServiceTypes.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
