# Description: Output filename
outputFile: openapi/openapi.yaml

# Description: Sort output files.
sortOutput: true

# Sort method arguments to place required parameters before optional parameters.
sortParamsByRequiredFlag: true

# Sort model properties to place required parameters before optional parameters.
sortModelPropertiesByRequiredFlag: true

# Ensure parameter names are unique
ensureUniqueParams: true

# Handle unknown enum cases gracefully for forward compatibility
enumUnknownDefaultCase: true
