/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "InterserverApiClient/model/LicensesOrder.h"

namespace net {
namespace interserver {
namespace api {
namespace model {

LicensesOrder::LicensesOrder()
{
    m_ServiceCategoriesIsSet = false;
    m_PackageCostsIsSet = false;
    m_ServiceTypesIsSet = false;
}

LicensesOrder::~LicensesOrder()
{
}

void LicensesOrder::validate()
{
    // TODO: implement validation
}

web::json::value LicensesOrder::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ServiceCategoriesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("serviceCategories"))] = ModelBase::toJson(m_ServiceCategories);
    }
    if(m_PackageCostsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageCosts"))] = ModelBase::toJson(m_PackageCosts);
    }
    if(m_ServiceTypesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("serviceTypes"))] = ModelBase::toJson(m_ServiceTypes);
    }

    return val;
}

bool LicensesOrder::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("serviceCategories"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("serviceCategories")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<LicensesOrder_serviceCategories> refVal_setServiceCategories;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceCategories);
            setServiceCategories(refVal_setServiceCategories);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageCosts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageCosts")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<LicensesOrder_packageCosts> refVal_setPackageCosts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageCosts);
            setPackageCosts(refVal_setPackageCosts);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("serviceTypes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("serviceTypes")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<LicensesOrder_serviceTypes> refVal_setServiceTypes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceTypes);
            setServiceTypes(refVal_setServiceTypes);
            
        }
    }
    return ok;
}

void LicensesOrder::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ServiceCategoriesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("serviceCategories")), m_ServiceCategories));
    }
    if(m_PackageCostsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageCosts")), m_PackageCosts));
    }
    if(m_ServiceTypesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("serviceTypes")), m_ServiceTypes));
    }
}

bool LicensesOrder::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("serviceCategories"))))
    {
        std::shared_ptr<LicensesOrder_serviceCategories> refVal_setServiceCategories;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("serviceCategories"))), refVal_setServiceCategories );
        setServiceCategories(refVal_setServiceCategories);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageCosts"))))
    {
        std::shared_ptr<LicensesOrder_packageCosts> refVal_setPackageCosts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageCosts"))), refVal_setPackageCosts );
        setPackageCosts(refVal_setPackageCosts);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("serviceTypes"))))
    {
        std::shared_ptr<LicensesOrder_serviceTypes> refVal_setServiceTypes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("serviceTypes"))), refVal_setServiceTypes );
        setServiceTypes(refVal_setServiceTypes);
    }
    return ok;
}


std::shared_ptr<LicensesOrder_serviceCategories> LicensesOrder::getServiceCategories() const
{
    return m_ServiceCategories;
}


void LicensesOrder::setServiceCategories(const std::shared_ptr<LicensesOrder_serviceCategories>& value)
{
    m_ServiceCategories = value;
    m_ServiceCategoriesIsSet = true;
}

bool LicensesOrder::serviceCategoriesIsSet() const
{
    return m_ServiceCategoriesIsSet;
}

void LicensesOrder::unsetServiceCategories()
{
    m_ServiceCategoriesIsSet = false;
}
std::shared_ptr<LicensesOrder_packageCosts> LicensesOrder::getPackageCosts() const
{
    return m_PackageCosts;
}


void LicensesOrder::setPackageCosts(const std::shared_ptr<LicensesOrder_packageCosts>& value)
{
    m_PackageCosts = value;
    m_PackageCostsIsSet = true;
}

bool LicensesOrder::packageCostsIsSet() const
{
    return m_PackageCostsIsSet;
}

void LicensesOrder::unsetPackageCosts()
{
    m_PackageCostsIsSet = false;
}
std::shared_ptr<LicensesOrder_serviceTypes> LicensesOrder::getServiceTypes() const
{
    return m_ServiceTypes;
}


void LicensesOrder::setServiceTypes(const std::shared_ptr<LicensesOrder_serviceTypes>& value)
{
    m_ServiceTypes = value;
    m_ServiceTypesIsSet = true;
}

bool LicensesOrder::serviceTypesIsSet() const
{
    return m_ServiceTypesIsSet;
}

void LicensesOrder::unsetServiceTypes()
{
    m_ServiceTypesIsSet = false;
}

}
}
}
}


