/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "InterserverApiClient/model/WebsitesOrderJsonServiceOffersItem.h"

namespace net {
namespace interserver {
namespace api {
namespace model {

WebsitesOrderJsonServiceOffersItem::WebsitesOrderJsonServiceOffersItem()
{
    m_Service_offer_id = utility::conversions::to_string_t("");
    m_Service_offer_idIsSet = false;
    m_Service_id = utility::conversions::to_string_t("");
    m_Service_idIsSet = false;
    m_Intro_cost = 0;
    m_Intro_costIsSet = false;
    m_Renewal_cost = 0;
    m_Renewal_costIsSet = false;
    m_Intro_frequency = utility::conversions::to_string_t("");
    m_Intro_frequencyIsSet = false;
    m_Renewal_frequency = utility::conversions::to_string_t("");
    m_Renewal_frequencyIsSet = false;
    m_Allow_coupon = utility::conversions::to_string_t("");
    m_Allow_couponIsSet = false;
    m_Service_module = utility::conversions::to_string_t("");
    m_Service_moduleIsSet = false;
    m_Created_at = utility::conversions::to_string_t("");
    m_Created_atIsSet = false;
    m_Updated_at = utility::conversions::to_string_t("");
    m_Updated_atIsSet = false;
    m_Deleted_at = utility::conversions::to_string_t("");
    m_Deleted_atIsSet = false;
    m_CurrencySymbol = utility::conversions::to_string_t("");
    m_CurrencySymbolIsSet = false;
}

WebsitesOrderJsonServiceOffersItem::~WebsitesOrderJsonServiceOffersItem()
{
}

void WebsitesOrderJsonServiceOffersItem::validate()
{
    // TODO: implement validation
}

web::json::value WebsitesOrderJsonServiceOffersItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Service_offer_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("service_offer_id"))] = ModelBase::toJson(m_Service_offer_id);
    }
    if(m_Service_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("service_id"))] = ModelBase::toJson(m_Service_id);
    }
    if(m_Intro_costIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("intro_cost"))] = ModelBase::toJson(m_Intro_cost);
    }
    if(m_Renewal_costIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("renewal_cost"))] = ModelBase::toJson(m_Renewal_cost);
    }
    if(m_Intro_frequencyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("intro_frequency"))] = ModelBase::toJson(m_Intro_frequency);
    }
    if(m_Renewal_frequencyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("renewal_frequency"))] = ModelBase::toJson(m_Renewal_frequency);
    }
    if(m_Allow_couponIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("allow_coupon"))] = ModelBase::toJson(m_Allow_coupon);
    }
    if(m_Service_moduleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("service_module"))] = ModelBase::toJson(m_Service_module);
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }
    if(m_Deleted_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deleted_at"))] = ModelBase::toJson(m_Deleted_at);
    }
    if(m_CurrencySymbolIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("currencySymbol"))] = ModelBase::toJson(m_CurrencySymbol);
    }

    return val;
}

bool WebsitesOrderJsonServiceOffersItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("service_offer_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("service_offer_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceOfferId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceOfferId);
            setServiceOfferId(refVal_setServiceOfferId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("service_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("service_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceId);
            setServiceId(refVal_setServiceId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("intro_cost"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("intro_cost")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setIntroCost;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIntroCost);
            setIntroCost(refVal_setIntroCost);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("renewal_cost"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("renewal_cost")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRenewalCost;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRenewalCost);
            setRenewalCost(refVal_setRenewalCost);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("intro_frequency"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("intro_frequency")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIntroFrequency;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIntroFrequency);
            setIntroFrequency(refVal_setIntroFrequency);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("renewal_frequency"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("renewal_frequency")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRenewalFrequency;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRenewalFrequency);
            setRenewalFrequency(refVal_setRenewalFrequency);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("allow_coupon"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("allow_coupon")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAllowCoupon;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAllowCoupon);
            setAllowCoupon(refVal_setAllowCoupon);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("service_module"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("service_module")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setServiceModule;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServiceModule);
            setServiceModule(refVal_setServiceModule);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deleted_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("currencySymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("currencySymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCurrencySymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurrencySymbol);
            setCurrencySymbol(refVal_setCurrencySymbol);
            
        }
    }
    return ok;
}

void WebsitesOrderJsonServiceOffersItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Service_offer_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("service_offer_id")), m_Service_offer_id));
    }
    if(m_Service_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("service_id")), m_Service_id));
    }
    if(m_Intro_costIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("intro_cost")), m_Intro_cost));
    }
    if(m_Renewal_costIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("renewal_cost")), m_Renewal_cost));
    }
    if(m_Intro_frequencyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("intro_frequency")), m_Intro_frequency));
    }
    if(m_Renewal_frequencyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("renewal_frequency")), m_Renewal_frequency));
    }
    if(m_Allow_couponIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("allow_coupon")), m_Allow_coupon));
    }
    if(m_Service_moduleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("service_module")), m_Service_module));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
    if(m_Deleted_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deleted_at")), m_Deleted_at));
    }
    if(m_CurrencySymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("currencySymbol")), m_CurrencySymbol));
    }
}

bool WebsitesOrderJsonServiceOffersItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("service_offer_id"))))
    {
        utility::string_t refVal_setServiceOfferId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("service_offer_id"))), refVal_setServiceOfferId );
        setServiceOfferId(refVal_setServiceOfferId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("service_id"))))
    {
        utility::string_t refVal_setServiceId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("service_id"))), refVal_setServiceId );
        setServiceId(refVal_setServiceId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("intro_cost"))))
    {
        int32_t refVal_setIntroCost;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("intro_cost"))), refVal_setIntroCost );
        setIntroCost(refVal_setIntroCost);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("renewal_cost"))))
    {
        int32_t refVal_setRenewalCost;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("renewal_cost"))), refVal_setRenewalCost );
        setRenewalCost(refVal_setRenewalCost);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("intro_frequency"))))
    {
        utility::string_t refVal_setIntroFrequency;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("intro_frequency"))), refVal_setIntroFrequency );
        setIntroFrequency(refVal_setIntroFrequency);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("renewal_frequency"))))
    {
        utility::string_t refVal_setRenewalFrequency;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("renewal_frequency"))), refVal_setRenewalFrequency );
        setRenewalFrequency(refVal_setRenewalFrequency);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("allow_coupon"))))
    {
        utility::string_t refVal_setAllowCoupon;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("allow_coupon"))), refVal_setAllowCoupon );
        setAllowCoupon(refVal_setAllowCoupon);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("service_module"))))
    {
        utility::string_t refVal_setServiceModule;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("service_module"))), refVal_setServiceModule );
        setServiceModule(refVal_setServiceModule);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::string_t refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::string_t refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))))
    {
        utility::string_t refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("currencySymbol"))))
    {
        utility::string_t refVal_setCurrencySymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("currencySymbol"))), refVal_setCurrencySymbol );
        setCurrencySymbol(refVal_setCurrencySymbol);
    }
    return ok;
}


utility::string_t WebsitesOrderJsonServiceOffersItem::getServiceOfferId() const
{
    return m_Service_offer_id;
}


void WebsitesOrderJsonServiceOffersItem::setServiceOfferId(const utility::string_t& value)
{
    m_Service_offer_id = value;
    m_Service_offer_idIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::serviceOfferIdIsSet() const
{
    return m_Service_offer_idIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetService_offer_id()
{
    m_Service_offer_idIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getServiceId() const
{
    return m_Service_id;
}


void WebsitesOrderJsonServiceOffersItem::setServiceId(const utility::string_t& value)
{
    m_Service_id = value;
    m_Service_idIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::serviceIdIsSet() const
{
    return m_Service_idIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetService_id()
{
    m_Service_idIsSet = false;
}
int32_t WebsitesOrderJsonServiceOffersItem::getIntroCost() const
{
    return m_Intro_cost;
}

void WebsitesOrderJsonServiceOffersItem::setIntroCost(int32_t value)
{
    m_Intro_cost = value;
    m_Intro_costIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::introCostIsSet() const
{
    return m_Intro_costIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetIntro_cost()
{
    m_Intro_costIsSet = false;
}
int32_t WebsitesOrderJsonServiceOffersItem::getRenewalCost() const
{
    return m_Renewal_cost;
}

void WebsitesOrderJsonServiceOffersItem::setRenewalCost(int32_t value)
{
    m_Renewal_cost = value;
    m_Renewal_costIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::renewalCostIsSet() const
{
    return m_Renewal_costIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetRenewal_cost()
{
    m_Renewal_costIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getIntroFrequency() const
{
    return m_Intro_frequency;
}


void WebsitesOrderJsonServiceOffersItem::setIntroFrequency(const utility::string_t& value)
{
    m_Intro_frequency = value;
    m_Intro_frequencyIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::introFrequencyIsSet() const
{
    return m_Intro_frequencyIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetIntro_frequency()
{
    m_Intro_frequencyIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getRenewalFrequency() const
{
    return m_Renewal_frequency;
}


void WebsitesOrderJsonServiceOffersItem::setRenewalFrequency(const utility::string_t& value)
{
    m_Renewal_frequency = value;
    m_Renewal_frequencyIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::renewalFrequencyIsSet() const
{
    return m_Renewal_frequencyIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetRenewal_frequency()
{
    m_Renewal_frequencyIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getAllowCoupon() const
{
    return m_Allow_coupon;
}


void WebsitesOrderJsonServiceOffersItem::setAllowCoupon(const utility::string_t& value)
{
    m_Allow_coupon = value;
    m_Allow_couponIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::allowCouponIsSet() const
{
    return m_Allow_couponIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetAllow_coupon()
{
    m_Allow_couponIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getServiceModule() const
{
    return m_Service_module;
}


void WebsitesOrderJsonServiceOffersItem::setServiceModule(const utility::string_t& value)
{
    m_Service_module = value;
    m_Service_moduleIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::serviceModuleIsSet() const
{
    return m_Service_moduleIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetService_module()
{
    m_Service_moduleIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getCreatedAt() const
{
    return m_Created_at;
}


void WebsitesOrderJsonServiceOffersItem::setCreatedAt(const utility::string_t& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getUpdatedAt() const
{
    return m_Updated_at;
}


void WebsitesOrderJsonServiceOffersItem::setUpdatedAt(const utility::string_t& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getDeletedAt() const
{
    return m_Deleted_at;
}


void WebsitesOrderJsonServiceOffersItem::setDeletedAt(const utility::string_t& value)
{
    m_Deleted_at = value;
    m_Deleted_atIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::deletedAtIsSet() const
{
    return m_Deleted_atIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetDeleted_at()
{
    m_Deleted_atIsSet = false;
}
utility::string_t WebsitesOrderJsonServiceOffersItem::getCurrencySymbol() const
{
    return m_CurrencySymbol;
}


void WebsitesOrderJsonServiceOffersItem::setCurrencySymbol(const utility::string_t& value)
{
    m_CurrencySymbol = value;
    m_CurrencySymbolIsSet = true;
}

bool WebsitesOrderJsonServiceOffersItem::currencySymbolIsSet() const
{
    return m_CurrencySymbolIsSet;
}

void WebsitesOrderJsonServiceOffersItem::unsetCurrencySymbol()
{
    m_CurrencySymbolIsSet = false;
}

}
}
}
}


