<?php
/**
 * ServerSwitchport
 *
 * PHP version 5
 *
 * @category Class
 * @package  InterserverApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * InterServer Management API
 *
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.81
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace InterserverApiClient\Model;

use \ArrayAccess;
use \InterserverApiClient\ObjectSerializer;

/**
 * ServerSwitchport Class Doc Comment
 *
 * @category Class
 * @package  InterserverApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerSwitchport implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ServerSwitchport';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'switchport_id' => 'int',
        'switch_id' => 'string',
        'switch' => 'string',
        'port' => 'string',
        'blade' => 'string',
        'justport' => 'string',
        'graph_id' => 'string',
        'vlans' => 'string[]',
        'vlans6' => 'string[]',
        'asset_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'switchport_id' => null,
        'switch_id' => null,
        'switch' => null,
        'port' => null,
        'blade' => null,
        'justport' => null,
        'graph_id' => null,
        'vlans' => null,
        'vlans6' => null,
        'asset_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'switchport_id' => 'switchport_id',
        'switch_id' => 'switch_id',
        'switch' => 'switch',
        'port' => 'port',
        'blade' => 'blade',
        'justport' => 'justport',
        'graph_id' => 'graph_id',
        'vlans' => 'vlans',
        'vlans6' => 'vlans6',
        'asset_id' => 'asset_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'switchport_id' => 'setSwitchportId',
        'switch_id' => 'setSwitchId',
        'switch' => 'setSwitch',
        'port' => 'setPort',
        'blade' => 'setBlade',
        'justport' => 'setJustport',
        'graph_id' => 'setGraphId',
        'vlans' => 'setVlans',
        'vlans6' => 'setVlans6',
        'asset_id' => 'setAssetId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'switchport_id' => 'getSwitchportId',
        'switch_id' => 'getSwitchId',
        'switch' => 'getSwitch',
        'port' => 'getPort',
        'blade' => 'getBlade',
        'justport' => 'getJustport',
        'graph_id' => 'getGraphId',
        'vlans' => 'getVlans',
        'vlans6' => 'getVlans6',
        'asset_id' => 'getAssetId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['switchport_id'] = isset($data['switchport_id']) ? $data['switchport_id'] : null;
        $this->container['switch_id'] = isset($data['switch_id']) ? $data['switch_id'] : null;
        $this->container['switch'] = isset($data['switch']) ? $data['switch'] : null;
        $this->container['port'] = isset($data['port']) ? $data['port'] : null;
        $this->container['blade'] = isset($data['blade']) ? $data['blade'] : null;
        $this->container['justport'] = isset($data['justport']) ? $data['justport'] : null;
        $this->container['graph_id'] = isset($data['graph_id']) ? $data['graph_id'] : null;
        $this->container['vlans'] = isset($data['vlans']) ? $data['vlans'] : null;
        $this->container['vlans6'] = isset($data['vlans6']) ? $data['vlans6'] : null;
        $this->container['asset_id'] = isset($data['asset_id']) ? $data['asset_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['switchport_id'] === null) {
            $invalidProperties[] = "'switchport_id' can't be null";
        }
        if ($this->container['switch_id'] === null) {
            $invalidProperties[] = "'switch_id' can't be null";
        }
        if ($this->container['switch'] === null) {
            $invalidProperties[] = "'switch' can't be null";
        }
        if ($this->container['port'] === null) {
            $invalidProperties[] = "'port' can't be null";
        }
        if ($this->container['blade'] === null) {
            $invalidProperties[] = "'blade' can't be null";
        }
        if ($this->container['justport'] === null) {
            $invalidProperties[] = "'justport' can't be null";
        }
        if ($this->container['graph_id'] === null) {
            $invalidProperties[] = "'graph_id' can't be null";
        }
        if ($this->container['asset_id'] === null) {
            $invalidProperties[] = "'asset_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets switchport_id
     *
     * @return int
     */
    public function getSwitchportId()
    {
        return $this->container['switchport_id'];
    }

    /**
     * Sets switchport_id
     *
     * @param int $switchport_id Unique identifier for the switchport.
     *
     * @return $this
     */
    public function setSwitchportId($switchport_id)
    {
        $this->container['switchport_id'] = $switchport_id;

        return $this;
    }

    /**
     * Gets switch_id
     *
     * @return string
     */
    public function getSwitchId()
    {
        return $this->container['switch_id'];
    }

    /**
     * Sets switch_id
     *
     * @param string $switch_id Unique identifier for the switch associated with the switchport.
     *
     * @return $this
     */
    public function setSwitchId($switch_id)
    {
        $this->container['switch_id'] = $switch_id;

        return $this;
    }

    /**
     * Gets switch
     *
     * @return string
     */
    public function getSwitch()
    {
        return $this->container['switch'];
    }

    /**
     * Sets switch
     *
     * @param string $switch Name of the switch associated with the switchport.
     *
     * @return $this
     */
    public function setSwitch($switch)
    {
        $this->container['switch'] = $switch;

        return $this;
    }

    /**
     * Gets port
     *
     * @return string
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param string $port Port name on the switch.
     *
     * @return $this
     */
    public function setPort($port)
    {
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets blade
     *
     * @return string
     */
    public function getBlade()
    {
        return $this->container['blade'];
    }

    /**
     * Sets blade
     *
     * @param string $blade Blade name associated with the port.
     *
     * @return $this
     */
    public function setBlade($blade)
    {
        $this->container['blade'] = $blade;

        return $this;
    }

    /**
     * Gets justport
     *
     * @return string
     */
    public function getJustport()
    {
        return $this->container['justport'];
    }

    /**
     * Sets justport
     *
     * @param string $justport Port identifier.
     *
     * @return $this
     */
    public function setJustport($justport)
    {
        $this->container['justport'] = $justport;

        return $this;
    }

    /**
     * Gets graph_id
     *
     * @return string
     */
    public function getGraphId()
    {
        return $this->container['graph_id'];
    }

    /**
     * Sets graph_id
     *
     * @param string $graph_id Identifier for the graph associated with the switchport.
     *
     * @return $this
     */
    public function setGraphId($graph_id)
    {
        $this->container['graph_id'] = $graph_id;

        return $this;
    }

    /**
     * Gets vlans
     *
     * @return string[]
     */
    public function getVlans()
    {
        return $this->container['vlans'];
    }

    /**
     * Sets vlans
     *
     * @param string[] $vlans List of VLANs associated with the switchport.
     *
     * @return $this
     */
    public function setVlans($vlans)
    {
        $this->container['vlans'] = $vlans;

        return $this;
    }

    /**
     * Gets vlans6
     *
     * @return string[]
     */
    public function getVlans6()
    {
        return $this->container['vlans6'];
    }

    /**
     * Sets vlans6
     *
     * @param string[] $vlans6 List of IPv6 VLANs associated with the switchport.
     *
     * @return $this
     */
    public function setVlans6($vlans6)
    {
        $this->container['vlans6'] = $vlans6;

        return $this;
    }

    /**
     * Gets asset_id
     *
     * @return int
     */
    public function getAssetId()
    {
        return $this->container['asset_id'];
    }

    /**
     * Sets asset_id
     *
     * @param int $asset_id Unique identifier of the asset associated with the switchport.
     *
     * @return $this
     */
    public function setAssetId($asset_id)
    {
        $this->container['asset_id'] = $asset_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
