# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""placeScrubOrder_201_response

    PlaceScrubOrder201Response(;
        success=nothing,
        text=nothing,
        order_details=nothing,
    )

    - success::Bool
    - text::String
    - order_details::PlaceScrubOrder201ResponseOrderDetails
"""
Base.@kwdef mutable struct PlaceScrubOrder201Response <: OpenAPI.APIModel
    success::Union{Nothing, Bool} = nothing
    text::Union{Nothing, String} = nothing
    order_details = nothing # spec type: Union{ Nothing, PlaceScrubOrder201ResponseOrderDetails }

    function PlaceScrubOrder201Response(success, text, order_details, )
        o = new(success, text, order_details, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PlaceScrubOrder201Response

const _property_types_PlaceScrubOrder201Response = Dict{Symbol,String}(Symbol("success")=>"Bool", Symbol("text")=>"String", Symbol("order_details")=>"PlaceScrubOrder201ResponseOrderDetails", )
OpenAPI.property_type(::Type{ PlaceScrubOrder201Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlaceScrubOrder201Response[name]))}

function OpenAPI.check_required(o::PlaceScrubOrder201Response)
    true
end

function OpenAPI.validate_properties(o::PlaceScrubOrder201Response)
    OpenAPI.validate_property(PlaceScrubOrder201Response, Symbol("success"), o.success)
    OpenAPI.validate_property(PlaceScrubOrder201Response, Symbol("text"), o.text)
    OpenAPI.validate_property(PlaceScrubOrder201Response, Symbol("order_details"), o.order_details)
end

function OpenAPI.validate_property(::Type{ PlaceScrubOrder201Response }, name::Symbol, val)



end
