# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""buyItNowServerOrder_200_response_cp_inner

    BuyItNowServerOrder200ResponseCpInner(;
        id=nothing,
        short_desc=nothing,
        long_desc=nothing,
        os_type=nothing,
        monthly_price=nothing,
    )

    - id::String
    - short_desc::String
    - long_desc::String
    - os_type::String
    - monthly_price::String
"""
Base.@kwdef mutable struct BuyItNowServerOrder200ResponseCpInner <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    short_desc::Union{Nothing, String} = nothing
    long_desc::Union{Nothing, String} = nothing
    os_type::Union{Nothing, String} = nothing
    monthly_price::Union{Nothing, String} = nothing

    function BuyItNowServerOrder200ResponseCpInner(id, short_desc, long_desc, os_type, monthly_price, )
        o = new(id, short_desc, long_desc, os_type, monthly_price, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BuyItNowServerOrder200ResponseCpInner

const _property_types_BuyItNowServerOrder200ResponseCpInner = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("short_desc")=>"String", Symbol("long_desc")=>"String", Symbol("os_type")=>"String", Symbol("monthly_price")=>"String", )
OpenAPI.property_type(::Type{ BuyItNowServerOrder200ResponseCpInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BuyItNowServerOrder200ResponseCpInner[name]))}

function OpenAPI.check_required(o::BuyItNowServerOrder200ResponseCpInner)
    true
end

function OpenAPI.validate_properties(o::BuyItNowServerOrder200ResponseCpInner)
    OpenAPI.validate_property(BuyItNowServerOrder200ResponseCpInner, Symbol("id"), o.id)
    OpenAPI.validate_property(BuyItNowServerOrder200ResponseCpInner, Symbol("short_desc"), o.short_desc)
    OpenAPI.validate_property(BuyItNowServerOrder200ResponseCpInner, Symbol("long_desc"), o.long_desc)
    OpenAPI.validate_property(BuyItNowServerOrder200ResponseCpInner, Symbol("os_type"), o.os_type)
    OpenAPI.validate_property(BuyItNowServerOrder200ResponseCpInner, Symbol("monthly_price"), o.monthly_price)
end

function OpenAPI.validate_property(::Type{ BuyItNowServerOrder200ResponseCpInner }, name::Symbol, val)





end
