# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""VpsServiceInfo

    VpsServiceInfo(;
        vps_id=nothing,
        vps_custid=nothing,
        vps_server=nothing,
        vps_ip=nothing,
        vps_ipv6=nothing,
        vps_vzid=nothing,
        vps_currency=nothing,
        vps_type=nothing,
        vps_order_date=nothing,
        vps_status=nothing,
        vps_invoice=nothing,
        vps_coupon=nothing,
        vps_extra=nothing,
        vps_hostname=nothing,
        vps_server_status=nothing,
        vps_comment=nothing,
        vps_slices=nothing,
        vps_vnc=nothing,
        vps_vnc_port=nothing,
        vps_rootpass=nothing,
        vps_mac=nothing,
        vps_os=nothing,
        vps_version=nothing,
        vps_location=nothing,
        vps_platform=nothing,
        vps_diskused=nothing,
        vps_diskmax=nothing,
    )

    - vps_id::String : VPS ID
    - vps_custid::String : Customer ID
    - vps_server::String : Server ID
    - vps_ip::String : IP address of the VPS
    - vps_ipv6::String : IPv6 address of the VPS
    - vps_vzid::String : VPS Virtuozzo ID
    - vps_currency::String : Currency used for billing
    - vps_type::String : VPS type
    - vps_order_date::String : Date of VPS order
    - vps_status::String : VPS status
    - vps_invoice::String : VPS invoice number
    - vps_coupon::String : VPS coupon code
    - vps_extra::String : Additional information about the VPS
    - vps_hostname::String : VPS hostname
    - vps_server_status::String : Status of the VPS server
    - vps_comment::String : Comment associated with the VPS
    - vps_slices::String : Number of VPS slices
    - vps_vnc::String : VNC address
    - vps_vnc_port::String : VNC port
    - vps_rootpass::String : Root password of the VPS
    - vps_mac::String : MAC address of the VPS
    - vps_os::String : Operating system of the VPS
    - vps_version::String : Version of the operating system
    - vps_location::String : Location of the VPS
    - vps_platform::String : Virtualization platform
    - vps_diskused::String : Amount of disk space used
    - vps_diskmax::String : Maximum disk space available
"""
Base.@kwdef mutable struct VpsServiceInfo <: OpenAPI.APIModel
    vps_id::Union{Nothing, String} = nothing
    vps_custid::Union{Nothing, String} = nothing
    vps_server::Union{Nothing, String} = nothing
    vps_ip::Union{Nothing, String} = nothing
    vps_ipv6::Union{Nothing, String} = nothing
    vps_vzid::Union{Nothing, String} = nothing
    vps_currency::Union{Nothing, String} = nothing
    vps_type::Union{Nothing, String} = nothing
    vps_order_date::Union{Nothing, String} = nothing
    vps_status::Union{Nothing, String} = nothing
    vps_invoice::Union{Nothing, String} = nothing
    vps_coupon::Union{Nothing, String} = nothing
    vps_extra::Union{Nothing, String} = nothing
    vps_hostname::Union{Nothing, String} = nothing
    vps_server_status::Union{Nothing, String} = nothing
    vps_comment::Union{Nothing, String} = nothing
    vps_slices::Union{Nothing, String} = nothing
    vps_vnc::Union{Nothing, String} = nothing
    vps_vnc_port::Union{Nothing, String} = nothing
    vps_rootpass::Union{Nothing, String} = nothing
    vps_mac::Union{Nothing, String} = nothing
    vps_os::Union{Nothing, String} = nothing
    vps_version::Union{Nothing, String} = nothing
    vps_location::Union{Nothing, String} = nothing
    vps_platform::Union{Nothing, String} = nothing
    vps_diskused::Union{Nothing, String} = nothing
    vps_diskmax::Union{Nothing, String} = nothing

    function VpsServiceInfo(vps_id, vps_custid, vps_server, vps_ip, vps_ipv6, vps_vzid, vps_currency, vps_type, vps_order_date, vps_status, vps_invoice, vps_coupon, vps_extra, vps_hostname, vps_server_status, vps_comment, vps_slices, vps_vnc, vps_vnc_port, vps_rootpass, vps_mac, vps_os, vps_version, vps_location, vps_platform, vps_diskused, vps_diskmax, )
        o = new(vps_id, vps_custid, vps_server, vps_ip, vps_ipv6, vps_vzid, vps_currency, vps_type, vps_order_date, vps_status, vps_invoice, vps_coupon, vps_extra, vps_hostname, vps_server_status, vps_comment, vps_slices, vps_vnc, vps_vnc_port, vps_rootpass, vps_mac, vps_os, vps_version, vps_location, vps_platform, vps_diskused, vps_diskmax, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VpsServiceInfo

const _property_types_VpsServiceInfo = Dict{Symbol,String}(Symbol("vps_id")=>"String", Symbol("vps_custid")=>"String", Symbol("vps_server")=>"String", Symbol("vps_ip")=>"String", Symbol("vps_ipv6")=>"String", Symbol("vps_vzid")=>"String", Symbol("vps_currency")=>"String", Symbol("vps_type")=>"String", Symbol("vps_order_date")=>"String", Symbol("vps_status")=>"String", Symbol("vps_invoice")=>"String", Symbol("vps_coupon")=>"String", Symbol("vps_extra")=>"String", Symbol("vps_hostname")=>"String", Symbol("vps_server_status")=>"String", Symbol("vps_comment")=>"String", Symbol("vps_slices")=>"String", Symbol("vps_vnc")=>"String", Symbol("vps_vnc_port")=>"String", Symbol("vps_rootpass")=>"String", Symbol("vps_mac")=>"String", Symbol("vps_os")=>"String", Symbol("vps_version")=>"String", Symbol("vps_location")=>"String", Symbol("vps_platform")=>"String", Symbol("vps_diskused")=>"String", Symbol("vps_diskmax")=>"String", )
OpenAPI.property_type(::Type{ VpsServiceInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VpsServiceInfo[name]))}

function OpenAPI.check_required(o::VpsServiceInfo)
    true
end

function OpenAPI.validate_properties(o::VpsServiceInfo)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_id"), o.vps_id)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_custid"), o.vps_custid)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_server"), o.vps_server)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_ip"), o.vps_ip)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_ipv6"), o.vps_ipv6)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_vzid"), o.vps_vzid)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_currency"), o.vps_currency)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_type"), o.vps_type)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_order_date"), o.vps_order_date)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_status"), o.vps_status)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_invoice"), o.vps_invoice)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_coupon"), o.vps_coupon)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_extra"), o.vps_extra)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_hostname"), o.vps_hostname)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_server_status"), o.vps_server_status)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_comment"), o.vps_comment)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_slices"), o.vps_slices)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_vnc"), o.vps_vnc)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_vnc_port"), o.vps_vnc_port)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_rootpass"), o.vps_rootpass)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_mac"), o.vps_mac)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_os"), o.vps_os)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_version"), o.vps_version)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_location"), o.vps_location)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_platform"), o.vps_platform)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_diskused"), o.vps_diskused)
    OpenAPI.validate_property(VpsServiceInfo, Symbol("vps_diskmax"), o.vps_diskmax)
end

function OpenAPI.validate_property(::Type{ VpsServiceInfo }, name::Symbol, val)



























end
