# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AccountInfoOauthConfigProviders_value

    AccountInfoOauthConfigProvidersValue(;
        enabled=nothing,
        linked=nothing,
        account=nothing,
        url=nothing,
    )

    - enabled::Bool
    - linked::Bool
    - account::String
    - url::String
"""
Base.@kwdef mutable struct AccountInfoOauthConfigProvidersValue <: OpenAPI.APIModel
    enabled::Union{Nothing, Bool} = nothing
    linked::Union{Nothing, Bool} = nothing
    account::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function AccountInfoOauthConfigProvidersValue(enabled, linked, account, url, )
        o = new(enabled, linked, account, url, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AccountInfoOauthConfigProvidersValue

const _property_types_AccountInfoOauthConfigProvidersValue = Dict{Symbol,String}(Symbol("enabled")=>"Bool", Symbol("linked")=>"Bool", Symbol("account")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ AccountInfoOauthConfigProvidersValue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AccountInfoOauthConfigProvidersValue[name]))}

function OpenAPI.check_required(o::AccountInfoOauthConfigProvidersValue)
    true
end

function OpenAPI.validate_properties(o::AccountInfoOauthConfigProvidersValue)
    OpenAPI.validate_property(AccountInfoOauthConfigProvidersValue, Symbol("enabled"), o.enabled)
    OpenAPI.validate_property(AccountInfoOauthConfigProvidersValue, Symbol("linked"), o.linked)
    OpenAPI.validate_property(AccountInfoOauthConfigProvidersValue, Symbol("account"), o.account)
    OpenAPI.validate_property(AccountInfoOauthConfigProvidersValue, Symbol("url"), o.url)
end

function OpenAPI.validate_property(::Type{ AccountInfoOauthConfigProvidersValue }, name::Symbol, val)




end
