# frozen_string_literal: true

# InterServer Management API
#
# The version of the OpenAPI document: 0.9.0
# Contact: support@interserver.net
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenapiClient
  module Models
    class DomainLookupResponse
      include OpenapiClient::Serializable
      include OpenapiClient::Validations

      attribute :available,
        type: 'Boolean',
        json_key: 'available',
        required: false

      attribute :premium,
        type: 'Boolean',
        json_key: 'premium',
        required: false

      attribute :website,
        type: 'Boolean',
        json_key: 'website',
        required: false

      attribute :domain_service,
        type: 'Boolean',
        json_key: 'domain_service',
        required: false

      attribute :service,
        type: 'Object',
        json_key: 'service',
        required: false

      attribute :whois_privacy,
        type: 'Boolean',
        json_key: 'whois_privacy',
        required: false

      attribute :new,
        type: 'String',
        json_key: 'new',
        required: false

      attribute :renewal,
        type: 'String',
        json_key: 'renewal',
        required: false

      attribute :transfer,
        type: 'String',
        json_key: 'transfer',
        required: false

      attribute :fields,
        type: 'Object',
        json_key: 'fields',
        required: false

      attribute :currencies,
        type: 'Object',
        json_key: 'currencies',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
