# frozen_string_literal: true

# InterServer Management API
#
# The version of the OpenAPI document: 0.9.0
# Contact: support@interserver.net
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module OpenapiClient
  module Models
    class MailDeliverabilityResponse
      include OpenapiClient::Serializable
      include OpenapiClient::Validations

      attribute :stat,
        type: 'Object',
        json_key: 'stat',
        required: false

      attribute :percent,
        type: 'Float',
        json_key: 'percent',
        required: false

      attribute :table_data,
        type: 'Array<Array<String>>',
        json_key: 'table_data',
        required: false

      def initialize(**attrs)
        attrs.each do |k, v|
          raise ArgumentError, "unknown attribute: #{k}" unless respond_to?("#{k}=")

          public_send("#{k}=", v)
        end
        raise ArgumentError, list_invalid_properties.join(', ') unless valid?
      end
    end
  end
end
