#
# InterServer Management API
# 
# # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
# The version of the OpenAPI document: 0.9.0
# Contact: support@interserver.net
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_charge_invoice_rows
import ../models/model_reverse_dns_entries
import ../models/model_service_order_post_response
import ../models/model_success_text_response
import ../models/model_text_response
import ../models/model_website
import ../models/model_website_backups
import ../models/model_website_login_response
import ../models/model_website_order_post_request
import ../models/model_website_order_put_request
import ../models/model_website_row
import ../models/model_websites_order
import ../models/model_get_account_info401response
import ../models/model_get_website_buy_ip200response
import ../models/model_post_website_buy_ip200response
import ../models/model_post_website_buy_ip_request
import ../models/model_post_website_migration200response
import ../models/model_post_website_migration_request
import ../models/model_post_website_migration_request1
import ../models/model_webhosting_cancel200response

const basepath = "https://my.interserver.net/apiv2"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc addWebsite*(httpClient: HttpClient, websiteOrderPostRequest: WebsiteOrderPostRequest): (Option[ServiceOrderPostResponse], Response) =
  ## Place a new webhosting order, create the invoice, and queue provisioning
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & "/websites/order", $(%websiteOrderPostRequest))
  constructResult[ServiceOrderPostResponse](response)


proc getNewWebsite*(httpClient: HttpClient): (Option[WebsitesOrder], Response) =
  ## Read the webhosting order catalog — plans, packages, promo offers, pricing

  let response = httpClient.get(basepath & "/websites/order")
  constructResult[WebsitesOrder](response)


proc getWebsiteBuyIp*(httpClient: HttpClient, id: int): (Option[getWebsiteBuyIp_200_response], Response) =
  ## Read website IPs, current reverse DNS, and additional-IP pricing

  let response = httpClient.get(basepath & fmt"/websites/{id}/buy_ip")
  constructResult[getWebsiteBuyIp_200_response](response)


proc getWebsiteInfo*(httpClient: HttpClient, id: int): (Option[Website], Response) =
  ## Read full configuration and status detail for one webhosting service

  let response = httpClient.get(basepath & fmt"/websites/{id}")
  constructResult[Website](response)


proc getWebsiteInvoices*(httpClient: HttpClient, id: int): (Option[ChargeInvoiceRows], Response) =
  ## List all billing invoices and recurring charges scoped to one website

  let response = httpClient.get(basepath & fmt"/websites/{id}/invoices")
  constructResult[ChargeInvoiceRows](response)


proc getWebsiteList*(httpClient: HttpClient): (Option[seq[WebsiteRow]], Response) =
  ## List the caller's webhosting (cPanel/DirectAdmin/Plesk/Webuzo) services

  let response = httpClient.get(basepath & "/websites")
  constructResult[seq[WebsiteRow]](response)


proc getWebsitesBackups*(httpClient: HttpClient, id: int): (Option[seq[WebsiteBackups_inner]], Response) =
  ## List off-site cpmove backups stored in Swift — list or inline-download archive

  let response = httpClient.get(basepath & fmt"/websites/{id}/backups")
  constructResult[seq[WebsiteBackups_inner]](response)


proc getWebsitesLogin*(httpClient: HttpClient, id: int): (Option[WebsiteLoginResponse], Response) =
  ## Get a one-time auto-login URL for the website's control panel

  let response = httpClient.get(basepath & fmt"/websites/{id}/login")
  constructResult[WebsiteLoginResponse](response)


proc getWebsitesWelcomeEmail*(httpClient: HttpClient, id: int): (Option[SuccessTextResponse], Response) =
  ## Resend the webhosting welcome email with control-panel credentials and URL

  let response = httpClient.get(basepath & fmt"/websites/{id}/welcome_email")
  constructResult[SuccessTextResponse](response)


proc gettWebsiteReverseDns*(httpClient: HttpClient, id: int): (Option[ReverseDnsEntries], Response) =
  ## Read current reverse-DNS (PTR) records for the website's IPs

  let response = httpClient.get(basepath & fmt"/websites/{id}/reverse_dns")
  constructResult[ReverseDnsEntries](response)


proc postWebsiteBuyIp*(httpClient: HttpClient, id: int, postWebsiteBuyIpRequest: PostWebsiteBuyIpRequest): (Option[postWebsiteBuyIp_200_response], Response) =
  ## Buy an additional IP for the website OR update reverse DNS records
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & fmt"/websites/{id}/buy_ip", $(%postWebsiteBuyIpRequest))
  constructResult[postWebsiteBuyIp_200_response](response)


proc postWebsiteMigration*(httpClient: HttpClient, id: int, postWebsiteMigrationRequest: PostWebsiteMigrationRequest): (Option[postWebsiteMigration_200_response], Response) =
  ## Submit a request for InterServer staff to migrate a website from another host
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & fmt"/websites/{id}/migration", $(%postWebsiteMigrationRequest))
  constructResult[postWebsiteMigration_200_response](response)


proc postWebsitesReverseDns*(httpClient: HttpClient, id: int, reverseDnsEntries: ReverseDnsEntries): (Option[TextResponse], Response) =
  ## Bulk-update reverse-DNS (PTR) records for one or more website IPs
  httpClient.headers["Content-Type"] = "application/json"

  let response = httpClient.post(basepath & fmt"/websites/{id}/reverse_dns", $(%reverseDnsEntries))
  constructResult[TextResponse](response)


proc putWebsites*(httpClient: HttpClient, websiteOrderPutRequest: WebsiteOrderPutRequest): Response =
  ## Validate a webhosting order and preview cost — dry run, no charge
  httpClient.headers["Content-Type"] = "application/json"
  httpClient.put(basepath & "/websites/order", $(%websiteOrderPutRequest))



proc updateWebsiteInfo*(httpClient: HttpClient, id: string): (Option[SuccessTextResponse], Response) =
  ## POST mutation hook for the website detail page (use dedicated ops where possible)

  let response = httpClient.post(basepath & fmt"/websites/{id}")
  constructResult[SuccessTextResponse](response)


proc webhostingCancel*(httpClient: HttpClient, id: string): (Option[webhostingCancel_200_response], Response) =
  ## Schedule termination of a webhosting service — wipes panel account at cycle end

  let response = httpClient.delete(basepath & fmt"/websites/{id}")
  constructResult[webhostingCancel_200_response](response)

