# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BackupsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BackupsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BackupsApi }) = "https://my.interserver.net/apiv2"

const _returntypes_add_backup_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BackupOrderPostResponse,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
    Regex("^" * replace("0", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_add_backup(_api::BackupsApi; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_add_backup_BackupsApi, "/backups/order", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.form, "validateOnly", validate_only)  # type Bool
    OpenAPI.Clients.set_param(_ctx.form, "serviceType", service_type)  # type Int64
    OpenAPI.Clients.set_param(_ctx.form, "coupon", coupon)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["multipart/form-data", "application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Place a new off-site backup storage order and generate the invoice

Step 3 of the backup-storage order flow. Revalidates via `validate_buy_storage()`, then calls `place_buy_storage()` which creates a `backups` service row, a `repeat_invoices` recurring entry, and the first `invoices` row. **Real billable order — call `validateBackupOrder` first.** Service is provisioned only after the invoice is paid. Sibling ops: `getNewBackup` (catalog), `validateBackupOrder` (quote), `getBackupInvoices` (billing history), `initiatePayment` (settle).  **Body fields** (JSON or multipart): - `serviceType` (integer, required) — `services_id` from `getNewBackup`. - `coupon` (string, optional) — coupon code. - `period` (integer, optional, default `1`) — billing months. - `comment` (string, optional) — saved on the order row.  **Returns** (on success): `{ continue: true, total_cost, iid, iids, real_iids, serviceId, invoice_description, cj_params }` — feed `real_iids` into `initiatePayment`. On validation failure: `{ continue: false, errors: [...] }` with HTTP 200.  **Auth:** Session/API key.  **Errors:** - `401` — unauthenticated. - `422` inside `errors[]` — coupon/plan/duplicate-hostname validation. - Explicit error text when no backend storage server is available for assignment.  **Side effects:** new rows in `backups`, `repeat_invoices`, `invoices`; queued provisioning kicks off only after payment.  **Related calls:** - **Prerequisite:** `validateBackupOrder`. - **Pay:** `getBillingInvoice` → `initiatePayment`. - **Poll status:** `getBackupInfo` (until `backup_status='active'`). 

Params:
- `validate_only`::`Bool`
- `service_type`::`Int64`
- `coupon`::`String`

Return: `BackupOrderPostResponse`, `OpenAPI.Clients.ApiResponse`
"""
function add_backup(_api::BackupsApi; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = _oacinternal_add_backup(_api; validate_only=validate_only, service_type=service_type, coupon=coupon, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function add_backup(_api::BackupsApi, response_stream::Channel; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = _oacinternal_add_backup(_api; validate_only=validate_only, service_type=service_type, coupon=coupon, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_cancel_backup_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => CancelBackup200Response,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_cancel_backup(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_cancel_backup_BackupsApi, "/backups/{id}", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Cancel an off-site backup storage subscription

DESTRUCTIVE. Use to terminate a backup-storage subscription. Delegates to `CancelService::go($id)` with module `backups`, which marks the service for cancellation and stops future recurring billing; data on the storage backend may become inaccessible at end of cycle. Path param: `id` from `getBackupsList`. No body. Returns `BackupsCancelResponse`. Caveats: irreversible — a new order via `addBackup` is required to restore service, with a new IP/username and no migration of prior data. Does NOT delete VPS/QS/webhosting in-place snapshots (those live under their own tags). Errors: HTTP 401 unauthenticated; HTTP 404 if `id` is not owned by the caller; HTTP 409 if the service is already cancelled or pending cancellation. Siblings: `addBackup`, `getBackupInfo`, `getBackupInvoices`.

Params:
- `id`::`Int64` (required)

Return: `CancelBackup200Response`, `OpenAPI.Clients.ApiResponse`
"""
function cancel_backup(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_cancel_backup(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function cancel_backup(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_cancel_backup(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_backup_info_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Backup,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_backup_info(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_backup_info_BackupsApi, "/backups/{id}", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get details of a specific off-site backup storage service

Use to fetch the full management view for one backup-storage subscription. Path param: `id` (backup service ID from `getBackupsList`). No body. Returns `serviceInfo` (with `backup_username`, `backup_ip`, `backup_status`, `backup_quota`, `backup_type`, `backup_invoice`), plus `billingDetails`, `extraInfoTables`, `package`, `custCurrency`, and `client_links` (rewritten to surface the link target rather than the raw queue URL). `admin_links`, internal `settings`, and `csrf` are stripped. Errors: HTTP 401 unauthenticated; HTTP 404 if `id` does not belong to the caller (cross-account access blocked by `get_service`). Siblings: `getBackupLogin` (open storage panel session), `getBackupInvoices`, `getBackupsWelcomeEmail`, `cancelBackup`, `updateBackupInfo`.

Params:
- `id`::`Int64` (required)

Return: `Backup`, `OpenAPI.Clients.ApiResponse`
"""
function get_backup_info(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_info(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_backup_info(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_info(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_backup_invoices_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ChargeInvoiceRows,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_backup_invoices(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_backup_invoices_BackupsApi, "/backups/{id}/invoices", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List invoices for a single backup-storage subscription

Use to retrieve all invoices tied to one off-site backup storage service — useful for confirming billing status, locating an unpaid invoice to pay, or reconciling renewals. Path param: `id` from `getBackupsList`. Delegates to the shared `InvoicesList::go()` handler with module `backups`. No body. Returns `ChargeInvoiceRows` (array of invoice rows with `invoices_id`, status, amount, dates). Feed `invoices_id` into `getBillingInvoice` for full detail or `/billing/pay/{method}/{invoices}` to settle an unpaid invoice. For the account-wide invoice list use the Billing tag instead. Errors: HTTP 401 unauthenticated; HTTP 404 if `id` is not owned by the caller. Siblings: `getBackupInfo`, `addBackup`.

Params:
- `id`::`Int64` (required)

Return: `ChargeInvoiceRows`, `OpenAPI.Clients.ApiResponse`
"""
function get_backup_invoices(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_invoices(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_backup_invoices(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_invoices(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_backup_login_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BackupLoginResponse,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_backup_login(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_backup_login_BackupsApi, "/backups/{id}/login", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Open a single sign-on session URL for the backup storage panel

Use to drop the customer straight into the off-site backup storage management panel without a separate login prompt. Calls `get_storage_session($id)` to mint a one-shot session URL; treat the URL as short-lived and credentials-equivalent — do not log or share. Path param: `id` from `getBackupsList`. No body. Returns `BackupLoginResponse` (`success`, session URL/token, optional connection hints). On `success=false` the handler returns `json_error(text)` (HTTP 400) with the upstream reason. Errors: HTTP 401 unauthenticated; HTTP 404 if `id` is not owned by the caller; backend errors when the storage server is unreachable. Siblings: `getBackupInfo` (SFTP `backup_username`/`backup_ip` for direct connections), `getBackupsWelcomeEmail` (resend setup credentials).

Params:
- `id`::`Int64` (required)

Return: `BackupLoginResponse`, `OpenAPI.Clients.ApiResponse`
"""
function get_backup_login(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_login(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_backup_login(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backup_login(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_backups_list_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{BackupRow},
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_backups_list(_api::BackupsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_backups_list_BackupsApi, "/backups", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List off-site backup storage subscriptions on the authenticated account

Use when enumerating all off-site backup storage services (SFTP-style remote storage subscriptions) on the authenticated customer's account. NOT for VPS/QS/webhosting in-place snapshots — those live under their own tags (`getVpsBackups`, `getQsBackups`, `getWebsitesBackups`). No query params, no body. Returns an array of rows; each row carries `backup_id`, `backup_name`, `backup_username`, `backup_status`, `services_name` (plan), and `backup_cost` (recurring price from `repeat_invoices`). Use `backup_id` as the path `{id}` for `getBackupInfo`, `getBackupLogin`, `getBackupInvoices`, `getBackupsWelcomeEmail`, `cancelBackup`. Errors: HTTP 401 if unauthenticated. Empty array when the customer has no backup services. Siblings: `getBackupInfo`, `getNewBackup`, `addBackup`.

Params:

Return: `Vector{BackupRow}`, `OpenAPI.Clients.ApiResponse`
"""
function get_backups_list(_api::BackupsApi; _mediaType=nothing)
    _ctx = _oacinternal_get_backups_list(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_backups_list(_api::BackupsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_backups_list(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_backups_welcome_email_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccessTextResponse,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_backups_welcome_email(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_backups_welcome_email_BackupsApi, "/backups/{id}/welcome_email", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Resend the welcome email for an off-site backup storage service

Use when the original welcome email was lost or never arrived. Resends connection credentials (SFTP host, username, quota) and setup instructions to the account email by invoking the module's `backup_welcome_email($id)` helper. Path param: `id` from `getBackupsList`. No body. Returns `SuccessTextResponse` with `text='Welcome Email has been resent.'`. Caveats: only works while the service is `active`; cancelled/pending services will return 409. Email is sent to the customer-of-record on file — there is no override recipient parameter. Errors: HTTP 401 unauthenticated; HTTP 404 if `id` is not owned by the caller (`Invalid Service Passed`); HTTP 409 if `backup_status` is not `active` (`Service is not active`). Siblings: `getBackupLogin`, `getBackupInfo`.

Params:
- `id`::`Int64` (required)

Return: `SuccessTextResponse`, `OpenAPI.Clients.ApiResponse`
"""
function get_backups_welcome_email(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backups_welcome_email(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_backups_welcome_email(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_backups_welcome_email(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_new_backup_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BackupsOrder,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_get_new_backup(_api::BackupsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_new_backup_BackupsApi, "/backups/order", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get backup-storage order form metadata and pricing tiers

Use before placing an off-site backup storage order to fetch the available plans, their service-type IDs, and per-tier pricing needed to render an order form. No params, no body. Returns `{ packageCosts, serviceTypes }` — `packageCosts` is a map of `services_id` → recurring cost (from `services` where `services_module='backups'` and `services_buyable=1`); `serviceTypes` is the dispatcher output of `run_event('get_service_types', true, 'backups')` describing each tier. Pass the chosen `services_id` as `serviceType` to `validateBackupOrder` (PUT) for a price preview, then to `addBackup` (POST) to commit. Errors: HTTP 401 if unauthenticated. Siblings: `validateBackupOrder`, `addBackup`, `getBackupsList`.

Params:

Return: `BackupsOrder`, `OpenAPI.Clients.ApiResponse`
"""
function get_new_backup(_api::BackupsApi; _mediaType=nothing)
    _ctx = _oacinternal_get_new_backup(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_new_backup(_api::BackupsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_new_backup(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_backup_info_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SuccessTextResponse,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_update_backup_info(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_update_backup_info_BackupsApi, "/backups/{id}", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Update stored metadata for a backup-storage subscription

Use to update non-billing metadata (e.g. stored credentials, comment, hostname) on an existing off-site backup storage service. Path param: `id` from `getBackupsList`. Body fields are forwarded to the same `View::go()` handler as the GET; consult the order form for accepted keys. Returns the standard `SuccessTextResponse`. Caveats: this endpoint does NOT change the plan, quota, or billing — those require cancel + reorder via `cancelBackup` and `addBackup`. It also does NOT trigger any backend SFTP credential rotation. Errors: HTTP 401 unauthenticated; HTTP 404 if `id` is not owned by the caller; HTTP 422 on invalid input. Siblings: `getBackupInfo`, `cancelBackup`, `getBackupLogin`.

Params:
- `id`::`Int64` (required)

Return: `SuccessTextResponse`, `OpenAPI.Clients.ApiResponse`
"""
function update_backup_info(_api::BackupsApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_update_backup_info(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_backup_info(_api::BackupsApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_update_backup_info(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_validate_backup_order_BackupsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BackupOrderPutResponse,
    Regex("^" * replace("401", "x"=>".") * "\$") => GetAccountInfo401Response,
)

function _oacinternal_validate_backup_order(_api::BackupsApi; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_validate_backup_order_BackupsApi, "/backups/order", ["sessionIdCookieAuth", "apiKeyAuth", "sessionIdHeaderAuth", ])
    OpenAPI.Clients.set_param(_ctx.form, "validateOnly", validate_only)  # type Bool
    OpenAPI.Clients.set_param(_ctx.form, "serviceType", service_type)  # type Int64
    OpenAPI.Clients.set_param(_ctx.form, "coupon", coupon)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["multipart/form-data", "application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Validate a backup-storage order and preview pricing without charging

Use to dry-run a backup order — runs `validate_buy_storage()` to compute final price, apply any coupon, and surface validation errors before the customer commits. No invoice is created and no service is provisioned. Body (JSON or multipart): `serviceType` (services_id from `getNewBackup`), optional `coupon`, `period` (months, default 1), `comment`. Returns `{ continue, errors, serviceType, serviceCost, originalCost, repeatServiceCost, hostname, password, coupon, couponCode }`. Use the response to render a confirmation screen, then call `addBackup` (POST same path) to place the order. Errors: HTTP 401 unauthenticated; HTTP 422 surfaced inside `errors[]` (invalid coupon, ineligible plan, duplicate hostname). Siblings: `addBackup`, `getNewBackup`.

Params:
- `validate_only`::`Bool`
- `service_type`::`Int64`
- `coupon`::`String`

Return: `BackupOrderPutResponse`, `OpenAPI.Clients.ApiResponse`
"""
function validate_backup_order(_api::BackupsApi; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = _oacinternal_validate_backup_order(_api; validate_only=validate_only, service_type=service_type, coupon=coupon, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function validate_backup_order(_api::BackupsApi, response_stream::Channel; validate_only=nothing, service_type=nothing, coupon=nothing, _mediaType=nothing)
    _ctx = _oacinternal_validate_backup_order(_api; validate_only=validate_only, service_type=service_type, coupon=coupon, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export add_backup
export cancel_backup
export get_backup_info
export get_backup_invoices
export get_backup_login
export get_backups_list
export get_backups_welcome_email
export get_new_backup
export update_backup_info
export validate_backup_order
