/*
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.81
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InterServerManagementApi);
  }
}(this, function(expect, InterServerManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SslOrderRequest', function() {
      beforeEach(function() {
        instance = new InterServerManagementApi.SslOrderRequest();
      });

      it('should create an instance of SslOrderRequest', function() {
        // TODO: update the code to test SslOrderRequest
        expect(instance).to.be.a(InterServerManagementApi.SslOrderRequest);
      });

      it('should have the property ssl (base name: "ssl")', function() {
        // TODO: update the code to test the property ssl
        expect(instance).to.have.property('ssl');
        // expect(instance.ssl).to.be(expectedValueLiteral);
      });

      it('should have the property hostname (base name: "hostname")', function() {
        // TODO: update the code to test the property hostname
        expect(instance).to.have.property('hostname');
        // expect(instance.hostname).to.be(expectedValueLiteral);
      });

      it('should have the property approver_email (base name: "approver_email")', function() {
        // TODO: update the code to test the property approver_email
        expect(instance).to.have.property('approver_email');
        // expect(instance.approver_email).to.be(expectedValueLiteral);
      });

      it('should have the property frequency (base name: "frequency")', function() {
        // TODO: update the code to test the property frequency
        expect(instance).to.have.property('frequency');
        // expect(instance.frequency).to.be(expectedValueLiteral);
      });

      it('should have the property coupon (base name: "coupon")', function() {
        // TODO: update the code to test the property coupon
        expect(instance).to.have.property('coupon');
        // expect(instance.coupon).to.be(expectedValueLiteral);
      });

      it('should have the property csr_type (base name: "csr_type")', function() {
        // TODO: update the code to test the property csr_type
        expect(instance).to.have.property('csr_type');
        // expect(instance.csr_type).to.be(expectedValueLiteral);
      });

      it('should have the property csr (base name: "csr")', function() {
        // TODO: update the code to test the property csr
        expect(instance).to.have.property('csr');
        // expect(instance.csr).to.be(expectedValueLiteral);
      });

      it('should have the property firstname (base name: "firstname")', function() {
        // TODO: update the code to test the property firstname
        expect(instance).to.have.property('firstname');
        // expect(instance.firstname).to.be(expectedValueLiteral);
      });

      it('should have the property lastname (base name: "lastname")', function() {
        // TODO: update the code to test the property lastname
        expect(instance).to.have.property('lastname');
        // expect(instance.lastname).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property address (base name: "address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property city (base name: "city")', function() {
        // TODO: update the code to test the property city
        expect(instance).to.have.property('city');
        // expect(instance.city).to.be(expectedValueLiteral);
      });

      it('should have the property state (base name: "state")', function() {
        // TODO: update the code to test the property state
        expect(instance).to.have.property('state');
        // expect(instance.state).to.be(expectedValueLiteral);
      });

      it('should have the property zip (base name: "zip")', function() {
        // TODO: update the code to test the property zip
        expect(instance).to.have.property('zip');
        // expect(instance.zip).to.be(expectedValueLiteral);
      });

      it('should have the property country (base name: "country")', function() {
        // TODO: update the code to test the property country
        expect(instance).to.have.property('country');
        // expect(instance.country).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

      it('should have the property company (base name: "company")', function() {
        // TODO: update the code to test the property company
        expect(instance).to.have.property('company');
        // expect(instance.company).to.be(expectedValueLiteral);
      });

      it('should have the property department (base name: "department")', function() {
        // TODO: update the code to test the property department
        expect(instance).to.have.property('department');
        // expect(instance.department).to.be(expectedValueLiteral);
      });

      it('should have the property agency (base name: "agency")', function() {
        // TODO: update the code to test the property agency
        expect(instance).to.have.property('agency');
        // expect(instance.agency).to.be(expectedValueLiteral);
      });

      it('should have the property business_category (base name: "business_category")', function() {
        // TODO: update the code to test the property business_category
        expect(instance).to.have.property('business_category');
        // expect(instance.business_category).to.be(expectedValueLiteral);
      });

    });
  });

}));
