/*
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.interserver.api.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

/**
 * Contact details used for domain registrant/admin/technical/billing records.
 **/
@ApiModel(description = "Contact details used for domain registrant/admin/technical/billing records.")
public class DomainContactDetails implements Serializable {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("org_name")
  private String orgName = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("postal_code")
  private String postalCode = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("fax")
  private String fax = null;
  @SerializedName("address2")
  private String address2 = null;
  @SerializedName("address3")
  private String address3 = null;
  @SerializedName("address1")
  private String address1 = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("last_name")
  private String lastName = null;

  /**
   * Contact status reported by the registrar.
   **/
  @ApiModelProperty(value = "Contact status reported by the registrar.")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * State or region for the contact address.
   **/
  @ApiModelProperty(value = "State or region for the contact address.")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   * Organization name for the contact.
   **/
  @ApiModelProperty(value = "Organization name for the contact.")
  public String getOrgName() {
    return orgName;
  }
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  /**
   * Two-letter country code for the contact.
   **/
  @ApiModelProperty(value = "Two-letter country code for the contact.")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   * Postal or ZIP code for the contact address.
   **/
  @ApiModelProperty(value = "Postal or ZIP code for the contact address.")
  public String getPostalCode() {
    return postalCode;
  }
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  /**
   * Email address for the contact.
   **/
  @ApiModelProperty(value = "Email address for the contact.")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Fax number for the contact, if available.
   **/
  @ApiModelProperty(value = "Fax number for the contact, if available.")
  public String getFax() {
    return fax;
  }
  public void setFax(String fax) {
    this.fax = fax;
  }

  /**
   * Secondary street address line.
   **/
  @ApiModelProperty(value = "Secondary street address line.")
  public String getAddress2() {
    return address2;
  }
  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  /**
   * Tertiary street address line.
   **/
  @ApiModelProperty(value = "Tertiary street address line.")
  public String getAddress3() {
    return address3;
  }
  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  /**
   * Primary street address line.
   **/
  @ApiModelProperty(value = "Primary street address line.")
  public String getAddress1() {
    return address1;
  }
  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  /**
   * City for the contact address.
   **/
  @ApiModelProperty(value = "City for the contact address.")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * Phone number for the contact.
   **/
  @ApiModelProperty(value = "Phone number for the contact.")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * First name for the contact.
   **/
  @ApiModelProperty(value = "First name for the contact.")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   * Last name for the contact.
   **/
  @ApiModelProperty(value = "Last name for the contact.")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainContactDetails domainContactDetails = (DomainContactDetails) o;
    return (this.status == null ? domainContactDetails.status == null : this.status.equals(domainContactDetails.status)) &&
        (this.state == null ? domainContactDetails.state == null : this.state.equals(domainContactDetails.state)) &&
        (this.orgName == null ? domainContactDetails.orgName == null : this.orgName.equals(domainContactDetails.orgName)) &&
        (this.country == null ? domainContactDetails.country == null : this.country.equals(domainContactDetails.country)) &&
        (this.postalCode == null ? domainContactDetails.postalCode == null : this.postalCode.equals(domainContactDetails.postalCode)) &&
        (this.email == null ? domainContactDetails.email == null : this.email.equals(domainContactDetails.email)) &&
        (this.fax == null ? domainContactDetails.fax == null : this.fax.equals(domainContactDetails.fax)) &&
        (this.address2 == null ? domainContactDetails.address2 == null : this.address2.equals(domainContactDetails.address2)) &&
        (this.address3 == null ? domainContactDetails.address3 == null : this.address3.equals(domainContactDetails.address3)) &&
        (this.address1 == null ? domainContactDetails.address1 == null : this.address1.equals(domainContactDetails.address1)) &&
        (this.city == null ? domainContactDetails.city == null : this.city.equals(domainContactDetails.city)) &&
        (this.phone == null ? domainContactDetails.phone == null : this.phone.equals(domainContactDetails.phone)) &&
        (this.firstName == null ? domainContactDetails.firstName == null : this.firstName.equals(domainContactDetails.firstName)) &&
        (this.lastName == null ? domainContactDetails.lastName == null : this.lastName.equals(domainContactDetails.lastName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.orgName == null ? 0: this.orgName.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.postalCode == null ? 0: this.postalCode.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.fax == null ? 0: this.fax.hashCode());
    result = 31 * result + (this.address2 == null ? 0: this.address2.hashCode());
    result = 31 * result + (this.address3 == null ? 0: this.address3.hashCode());
    result = 31 * result + (this.address1 == null ? 0: this.address1.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainContactDetails {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  orgName: ").append(orgName).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  postalCode: ").append(postalCode).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  fax: ").append(fax).append("\n");
    sb.append("  address2: ").append(address2).append("\n");
    sb.append("  address3: ").append(address3).append("\n");
    sb.append("  address1: ").append(address1).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
