=begin
#InterServer Management API

## Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  

The version of the OpenAPI document: 0.9.0
Contact: support@interserver.net
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module InterServerClient
  # Request payload for enabling or disabling Whois privacy.
  class DomainWhoisPrivacyRequest < ApiModelBase
    # Action to perform (enable or disableCancel).
    attr_accessor :func

    # CSRF token if the API requires it for the account.
    attr_accessor :csrf_token

    attr_accessor :domain_firstname

    attr_accessor :domain_lastname

    attr_accessor :domain_email

    attr_accessor :domain_address

    attr_accessor :domain_address2

    attr_accessor :domain_address3

    attr_accessor :domain_city

    attr_accessor :domain_state

    attr_accessor :domain_zip

    attr_accessor :domain_country

    attr_accessor :domain_phone

    attr_accessor :domain_fax

    attr_accessor :domain_company

    attr_accessor :domain_extra

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'func' => :'func',
        :'csrf_token' => :'csrf_token',
        :'domain_firstname' => :'domain_firstname',
        :'domain_lastname' => :'domain_lastname',
        :'domain_email' => :'domain_email',
        :'domain_address' => :'domain_address',
        :'domain_address2' => :'domain_address2',
        :'domain_address3' => :'domain_address3',
        :'domain_city' => :'domain_city',
        :'domain_state' => :'domain_state',
        :'domain_zip' => :'domain_zip',
        :'domain_country' => :'domain_country',
        :'domain_phone' => :'domain_phone',
        :'domain_fax' => :'domain_fax',
        :'domain_company' => :'domain_company',
        :'domain_extra' => :'domain_extra'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'func' => :'String',
        :'csrf_token' => :'String',
        :'domain_firstname' => :'String',
        :'domain_lastname' => :'String',
        :'domain_email' => :'String',
        :'domain_address' => :'String',
        :'domain_address2' => :'String',
        :'domain_address3' => :'String',
        :'domain_city' => :'String',
        :'domain_state' => :'String',
        :'domain_zip' => :'String',
        :'domain_country' => :'String',
        :'domain_phone' => :'String',
        :'domain_fax' => :'String',
        :'domain_company' => :'String',
        :'domain_extra' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `InterServerClient::DomainWhoisPrivacyRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `InterServerClient::DomainWhoisPrivacyRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'func')
        self.func = attributes[:'func']
      end

      if attributes.key?(:'csrf_token')
        self.csrf_token = attributes[:'csrf_token']
      end

      if attributes.key?(:'domain_firstname')
        self.domain_firstname = attributes[:'domain_firstname']
      end

      if attributes.key?(:'domain_lastname')
        self.domain_lastname = attributes[:'domain_lastname']
      end

      if attributes.key?(:'domain_email')
        self.domain_email = attributes[:'domain_email']
      end

      if attributes.key?(:'domain_address')
        self.domain_address = attributes[:'domain_address']
      end

      if attributes.key?(:'domain_address2')
        self.domain_address2 = attributes[:'domain_address2']
      end

      if attributes.key?(:'domain_address3')
        self.domain_address3 = attributes[:'domain_address3']
      end

      if attributes.key?(:'domain_city')
        self.domain_city = attributes[:'domain_city']
      end

      if attributes.key?(:'domain_state')
        self.domain_state = attributes[:'domain_state']
      end

      if attributes.key?(:'domain_zip')
        self.domain_zip = attributes[:'domain_zip']
      end

      if attributes.key?(:'domain_country')
        self.domain_country = attributes[:'domain_country']
      end

      if attributes.key?(:'domain_phone')
        self.domain_phone = attributes[:'domain_phone']
      end

      if attributes.key?(:'domain_fax')
        self.domain_fax = attributes[:'domain_fax']
      end

      if attributes.key?(:'domain_company')
        self.domain_company = attributes[:'domain_company']
      end

      if attributes.key?(:'domain_extra')
        self.domain_extra = attributes[:'domain_extra']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          func == o.func &&
          csrf_token == o.csrf_token &&
          domain_firstname == o.domain_firstname &&
          domain_lastname == o.domain_lastname &&
          domain_email == o.domain_email &&
          domain_address == o.domain_address &&
          domain_address2 == o.domain_address2 &&
          domain_address3 == o.domain_address3 &&
          domain_city == o.domain_city &&
          domain_state == o.domain_state &&
          domain_zip == o.domain_zip &&
          domain_country == o.domain_country &&
          domain_phone == o.domain_phone &&
          domain_fax == o.domain_fax &&
          domain_company == o.domain_company &&
          domain_extra == o.domain_extra
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [func, csrf_token, domain_firstname, domain_lastname, domain_email, domain_address, domain_address2, domain_address3, domain_city, domain_state, domain_zip, domain_country, domain_phone, domain_fax, domain_company, domain_extra].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
