# NOTE: This file is auto generated by OpenAPI Generator 7.24.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule InterserverApi.Model.GetScrubIpDetails200ResponseFilterFirewall do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :rules,
    :filters,
    :scrub_enabled
  ]

  @type t :: %__MODULE__{
    :rules => [InterserverApi.Model.GetScrubIpDetails200ResponseFilterFirewallRulesInner.t] | nil,
    :filters => [InterserverApi.Model.GetScrubIpDetails200ResponseFilterFirewallFiltersInner.t] | nil,
    :scrub_enabled => integer() | nil
  }

  alias InterserverApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rules, :list, InterserverApi.Model.GetScrubIpDetails200ResponseFilterFirewallRulesInner)
     |> Deserializer.deserialize(:filters, :list, InterserverApi.Model.GetScrubIpDetails200ResponseFilterFirewallFiltersInner)
  end
end

