require "json"

module InterserverApiClient
  module Api
  class Billing::Creditcards
    def initialize(@conn : Connection); end

    # Store a credit card on the account — may return a verification flow Stores a new credit card on the account so it can later be selected via &#x60;updateBillingPaymentMethod&#x60; or used directly with &#x60;initiatePayment&#x60; (&#x60;method&#x3D;cc&#x60;). The card number has dashes stripped and is sanitized through &#x60;FILTER_SANITIZE_NUMBER_INT&#x60;; billing address fields are HTML-entity-escaped server-side; the CC number is encrypted at rest via &#x60;App::encrypt()&#x60;. The flow may return &#x60;action&#x3D;&#39;verify&#39;&#x60; indicating a two-step micro-charge verification is required before the card is usable — complete it with &#x60;patchBillingCreditCardVerify&#x60; then &#x60;postBillingCreditCardVerify&#x60;. Sibling ops: &#x60;updateBillingCreditCard&#x60;, &#x60;deleteBillingCreditCard&#x60;, &#x60;patchBillingCreditCardVerify&#x60;, &#x60;postBillingCreditCardVerify&#x60;, &#x60;updateBillingPaymentMethod&#x60;.  **Body fields (JSON or multipart, schema &#x60;BillingAddCcRequest&#x60;):** - &#x60;cc&#x60; (string, required) — card number; dashes stripped, non-digits filtered. - &#x60;name&#x60; (string, required) — cardholder name. - &#x60;cc_exp&#x60; (string, required) — &#x60;MM/YYYY&#x60;. - &#x60;address&#x60; (string, required), &#x60;city&#x60;, &#x60;state&#x60;, &#x60;country&#x60;, &#x60;zip&#x60; (strings) — billing address; HTML-entity-escaped.  **Returns:** - **Added directly:** &#x60;{success: true, text: \&quot;Card Added Successfully!\&quot;}&#x60;. - **Verification needed:** &#x60;{success: false, text: \&quot;Kindly verify your card by updating the amounts in the fields\&quot;, action: \&quot;verify\&quot;}&#x60; — proceed to &#x60;patchBillingCreditCardVerify&#x60;.  **Side effects:** - Inserts the encrypted card into the account&#39;s &#x60;ccs&#x60; array (managed via &#x60;parse_ccs&#x60; / &#x60;add_cc&#x60;). - May trigger a small initial test charge (gateway-dependent). - First-card-on-account triggers MaxMind + FraudRecord risk-score recomputation.  **Auth:** Session/API key.  **Errors:** - &#x60;Card number, Full Name, Expiry date are required!&#x60; — required field missing/empty. - &#x60;401&#x60; — unauthenticated. - Gateway/AVS error text — declined, mismatch, etc.  **Related calls:** - **Verify (if &#x60;action&#x3D;&#39;verify&#39;&#x60;):** &#x60;patchBillingCreditCardVerify&#x60; (CVV + initiate micro-charge) → &#x60;postBillingCreditCardVerify&#x60; (submit amounts). - **Make it the default:** &#x60;updateBillingPaymentMethod&#x60; with &#x60;payment_method&#x3D;cc&lt;idx&gt;&#x60;. - **Pay an invoice with it:** &#x60;initiatePayment&#x60; (&#x60;method&#x3D;cc&#x60;). 
    def create(billing_add_cc_request : InterserverApiClient::BillingAddCcRequest) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :POST,
        path: "/billing/creditcards",
        body: billing_add_cc_request,
        accept: %w[application/json],
        content_type: %w[application/json multipart/form-data],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end

    # Refresh stored card expiration and re-trigger MaxMind fraud scoring Updates the expiration date on a stored credit card and re-encrypts the card record. If the updated card matches the account&#39;s primary &#x60;cc&#x60;, the account-level &#x60;cc_exp&#x60; is also refreshed. If no MaxMind risk score exists yet for the card, &#x60;update_maxmind()&#x60; is called to compute one. Use to fix an upcoming expiration before recurring charges fail. Sibling ops: &#x60;addBillingCreditCard&#x60;, &#x60;deleteBillingCreditCard&#x60;, &#x60;getBillingCreditCardVerify&#x60;, &#x60;postBillingCreditCardVerify&#x60;, &#x60;updateBillingPaymentMethod&#x60;.  **Path param:** - &#x60;id&#x60; (integer, required) — credit card index (the key in the account&#39;s &#x60;ccs&#x60; array, returned by &#x60;parse_ccs&#x60; and surfaced as &#x60;cc&lt;idx&gt;&#x60; in &#x60;updateBillingPaymentMethod&#x60;).  **Body fields:** - &#x60;cc_exp&#x60; (string, required) — new expiration in &#x60;MM/YYYY&#x60; format.  **Returns:** &#x60;Card updated successfully.&#x60;.  **Side effects:** - Updates the &#x60;ccs&#x60; array (re-serialized via &#x60;myadmin_stringify&#x60;) on the account. - When the card &#x3D;&#x3D; primary &#x60;cc&#x60;, the account-level &#x60;cc_exp&#x60; is also written. - Triggers &#x60;update_maxmind($custid, false, $cc_idx)&#x60; if no risk score exists.  **Auth:** Session/API key. Card ownership enforced via &#x60;parse_ccs&#x60;.  **Errors:** - &#x60;Invalid Credit Card Passed&#x60; — &#x60;id&#x60; not in &#x60;parse_ccs&#x60;. - &#x60;Please enter valid card expiry date&#x60; — &#x60;cc_exp&#x60; body field missing. - &#x60;Invalid expiration date. It must be in the form of MM/YYYY&#x60; — wrong format. - &#x60;401&#x60; — unauthenticated.  **Related calls:** - **Verify a freshly added card:** &#x60;patchBillingCreditCardVerify&#x60; → &#x60;postBillingCreditCardVerify&#x60;. - **Remove the card:** &#x60;deleteBillingCreditCard&#x60;. - **Make it default:** &#x60;updateBillingPaymentMethod&#x60; with &#x60;payment_method&#x3D;cc&lt;idx&gt;&#x60;. 
    def create_post(id : Int32) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :POST,
        path: "/billing/creditcards/{id}".sub("{id}", InterserverApiClient.enc(id)),
        accept: %w[application/json],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end

    # Remove a stored credit card from the account Removes the indexed credit card from the account&#39;s &#x60;ccs&#x60; collection. If the deleted card was also the account&#39;s primary &#x60;cc&#x60;, the primary field is cleared — &#x60;initiatePayment&#x60; (&#x60;method&#x3D;cc&#x60;) will then return an error until a new default is designated via &#x60;updateBillingPaymentMethod&#x60;. **Irreversible** — to re-store the same card, re-run &#x60;addBillingCreditCard&#x60;. Sibling ops: &#x60;addBillingCreditCard&#x60;, &#x60;updateBillingCreditCard&#x60;, &#x60;updateBillingPaymentMethod&#x60;, &#x60;getBillingCreditCardVerify&#x60;.  **Path param:** - &#x60;id&#x60; (integer, required) — credit card index from &#x60;parse_ccs&#x60;.  **Body:** None.  **Returns:** &#x60;Card removed successfully.&#x60;.  **Side effects:** - Removes the entry from the &#x60;ccs&#x60; array; re-serialized via &#x60;myadmin_stringify&#x60;. - When the deleted card was primary: clears account-level &#x60;cc&#x60;.  **Auth:** Session/API key. Card ownership enforced.  **Errors:** - &#x60;Invalid Credit Card Passed&#x60; — &#x60;id&#x60; not in &#x60;parse_ccs&#x60;. - &#x60;401&#x60; — unauthenticated.  **Related calls:** - **Set a new default:** &#x60;updateBillingPaymentMethod&#x60;. - **Add a replacement:** &#x60;addBillingCreditCard&#x60;. 
    def delete(id : Int32) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :DELETE,
        path: "/billing/creditcards/{id}".sub("{id}", InterserverApiClient.enc(id)),
        accept: %w[application/json],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end

    # Probe whether a stored card still needs micro-charge verification Status probe for the credit-card verification flow. Read-only — current implementation returns a placeholder string indicating verification is pending; the actual two-step verification happens via &#x60;patchBillingCreditCardVerify&#x60; (initiate dual micro-charge with CVV) followed by &#x60;postBillingCreditCardVerify&#x60; (submit the charged amounts). Use to drive the UI&#39;s \&quot;verify card\&quot; form rendering. Sibling ops: &#x60;patchBillingCreditCardVerify&#x60;, &#x60;postBillingCreditCardVerify&#x60;, &#x60;addBillingCreditCard&#x60;, &#x60;updateBillingPaymentMethod&#x60;.  **Path param:** - &#x60;id&#x60; (integer, required) — credit card index from &#x60;parse_ccs&#x60;.  **Body:** None.  **Returns:** &#x60;Verification requirements&#x60; (placeholder text — reserved for future structured response with &#x60;requires_cvv&#x60; / &#x60;requires_amounts&#x60; flags).  **Auth:** Session/API key.  **Errors:** - &#x60;401&#x60; — unauthenticated.  **Related calls:** - **Step 1 of verify flow:** &#x60;patchBillingCreditCardVerify&#x60;. - **Step 2 of verify flow:** &#x60;postBillingCreditCardVerify&#x60;. - **Add a new card:** &#x60;addBillingCreditCard&#x60;. 
    def verify(id : Int32) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :GET,
        path: "/billing/creditcards/{id}/verify".sub("{id}", InterserverApiClient.enc(id)),
        accept: %w[application/json],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end

    # Place two micro-charges on the card to start CVV verification (step 1 of 2) Step 1 of the two-step card-verification flow. After &#x60;addBillingCreditCard&#x60; returns &#x60;action&#x3D;&#39;verify&#39;&#x60;, call this with the card&#39;s CVV to place two small charges (cents-scale) on the card. The customer must then look up the exact amounts in their bank statement and submit them via &#x60;postBillingCreditCardVerify&#x60; to finalize verification. **After 3 failed CVV attempts** (&#x60;cc_fails_&lt;cc&gt;&#x60; counter on the account) the card is locked from further verification attempts — contact support. Sibling ops: &#x60;getBillingCreditCardVerify&#x60;, &#x60;postBillingCreditCardVerify&#x60;, &#x60;addBillingCreditCard&#x60;, &#x60;updateBillingPaymentMethod&#x60;.  **Path param:** - &#x60;id&#x60; (integer, required) — credit card index from &#x60;parse_ccs&#x60;.  **Body fields:** - &#x60;cc_ccv2&#x60; (string, required) — the 3- or 4-digit CVV/CVC code from the back (or front, for Amex) of the card.  **Returns:** &#x60;Your card is charged. Please enter the amounts charged up!&#x60; — surface to the UI to prompt for the two amounts.  **Side effects:** - Places two test charges via &#x60;verify_cc_charge()&#x60; (gateway-side). - On failure: increments &#x60;cc_fails_&lt;cc&gt;&#x60; on the account.  **Auth:** Session/API key. Card ownership enforced.  **Errors:** - &#x60;Invalid Credit Card Passed&#x60; — &#x60;id&#x60; not in &#x60;parse_ccs&#x60;. - &#x60;Reached the max number of tries to authenticate this card&#x60; — &#x60;cc_fails_&lt;cc&gt; &gt; 3&#x60;. - &#x60;Missing or blank CVV&#x60; — &#x60;cc_ccv2&#x60; absent or empty. - Gateway error text — charge attempt failed. - &#x60;401&#x60; — unauthenticated.  **Related calls:** - **Prerequisite:** &#x60;addBillingCreditCard&#x60; (must have returned &#x60;action&#x3D;&#39;verify&#39;&#x60;). - **Next (step 2):** &#x60;postBillingCreditCardVerify&#x60; (submit &#x60;cc_amount1&#x60; + &#x60;cc_amount2&#x60;). - **After verification:** &#x60;updateBillingPaymentMethod&#x60; to make it the default. 
    def verify_patch(id : Int32, patch_billing_credit_card_verify_request : InterserverApiClient::PatchBillingCreditCardVerifyRequest) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :PATCH,
        path: "/billing/creditcards/{id}/verify".sub("{id}", InterserverApiClient.enc(id)),
        body: patch_billing_credit_card_verify_request,
        accept: %w[application/json],
        content_type: %w[application/json multipart/form-data],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end

    # Submit two micro-charge amounts to finalize card verification (step 2 of 2) Step 2 of the two-step card-verification flow. Submits the two exact micro-charge amounts the customer saw on their statement (placed by &#x60;patchBillingCreditCardVerify&#x60;) so the gateway can confirm the customer controls the card. On success, the card is marked verified and can be selected via &#x60;updateBillingPaymentMethod&#x60; (&#x60;payment_method&#x3D;cc&lt;idx&gt;&#x60;) or used directly with &#x60;initiatePayment&#x60; (&#x60;method&#x3D;cc&#x60;). After 3 failed attempts (&#x60;cc_fails_&lt;cc&gt; &gt; 3&#x60;) the card is locked. Sibling ops: &#x60;getBillingCreditCardVerify&#x60;, &#x60;patchBillingCreditCardVerify&#x60;, &#x60;addBillingCreditCard&#x60;, &#x60;updateBillingPaymentMethod&#x60;.  **Path param:** - &#x60;id&#x60; (integer, required) — credit card index from &#x60;parse_ccs&#x60;.  **Body fields (schema &#x60;BillingVerifyCcRequest&#x60;):** - &#x60;cc_amount1&#x60; (number, required) — first micro-charge amount (in dollars, decimal). - &#x60;cc_amount2&#x60; (number, required) — second micro-charge amount.  **Returns:** Verification success text (gateway-returned).  **Side effects:** - Marks the card as verified when amounts match. - On failure: increments &#x60;cc_fails_&lt;cc&gt;&#x60; on the account.  **Auth:** Session/API key. Card ownership enforced.  **Errors:** - &#x60;Invalid Credit Card Passed&#x60; — &#x60;id&#x60; not in &#x60;parse_ccs&#x60;. - &#x60;Reached the max number of tries to authenticate this card&#x60; — &#x60;cc_fails_&lt;cc&gt; &gt; 3&#x60;. - &#x60;Missing charge amounts&#x60; — &#x60;cc_amount1&#x60; or &#x60;cc_amount2&#x60; absent. - Verification failure text (status &#x60;failed&#x60; / &#x60;error&#x60; / &#x60;warning&#x60;) — amounts don&#39;t match. - &#x60;401&#x60; — unauthenticated.  **Related calls:** - **Prerequisite (step 1):** &#x60;patchBillingCreditCardVerify&#x60;. - **Next:** &#x60;updateBillingPaymentMethod&#x60; to make the verified card default, or &#x60;initiatePayment&#x60; (&#x60;method&#x3D;cc&#x60;) to pay immediately. 
    def verify_post(id : Int32, billing_verify_cc_request : InterserverApiClient::BillingVerifyCcRequest) : Response(InterserverApiClient::SuccessTextResponse)
      @conn.request(InterserverApiClient::SuccessTextResponse,
        method: :POST,
        path: "/billing/creditcards/{id}/verify".sub("{id}", InterserverApiClient.enc(id)),
        body: billing_verify_cc_request,
        accept: %w[application/json],
        content_type: %w[application/json multipart/form-data],
        auth: %w[sessionIdCookieAuth apiKeyAuth sessionIdHeaderAuth])
    end
  end
  end

end
