//
// FloatingIpOrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request body to validate (putFloating_ips) or place (addFloatingIp) a floating IP order. Service type ids come from getNewFloatingIp.serviceTypes. */
open class FloatingIpOrderRequest: JSONEncodable {
    /** Floating IP plan service type id from getNewFloatingIp.serviceTypes (must be buyable). */
    public var serviceType: Int32?
    /** Coupon code. */
    public var coupon: String?
    /** Free-form note saved on the service row (used on addFloatingIp). */
    public var comment: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["serviceType"] = self.serviceType?.encodeToJSON()
        nillableDictionary["coupon"] = self.coupon
        nillableDictionary["comment"] = self.comment

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
