/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "DnsRecord.h"

#include <cstddef>
#include <map>
#include <memory>
#include <stdexcept>
#include <sstream>
#include <string>
#include <iterator>
#include <utility>
#include <vector>
#include <algorithm>
#include <array>
#include <boost/json.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace {
template<typename EnumValue, std::size_t Size>
void validateEnumValues(
    const EnumValue& value,
    const std::array<EnumValue, Size>& allowedValues);

template<typename Element, typename EnumValue, std::size_t Size>
void validateEnumValues(
    const std::vector<Element>& values,
    const std::array<EnumValue, Size>& allowedValues);

template<typename MappedValue, typename EnumValue, std::size_t Size>
void validateEnumValues(
    const std::map<std::string, MappedValue>& values,
    const std::array<EnumValue, Size>& allowedValues);

template<typename EnumValue, std::size_t Size>
void validateEnumValues(
    const EnumValue& value,
    const std::array<EnumValue, Size>& allowedValues)
{
    if (std::find(allowedValues.begin(), allowedValues.end(), value) == allowedValues.end()) {
        std::ostringstream errorMessage;
        errorMessage << "Value " << value << " not allowed";
        throw std::runtime_error(errorMessage.str());
    }
}

template<typename Element, typename EnumValue, std::size_t Size>
void validateEnumValues(
    const std::vector<Element>& values,
    const std::array<EnumValue, Size>& allowedValues)
{
    for (const auto& value : values) {
        validateEnumValues(value, allowedValues);
    }
}

template<typename MappedValue, typename EnumValue, std::size_t Size>
void validateEnumValues(
    const std::map<std::string, MappedValue>& values,
    const std::array<EnumValue, Size>& allowedValues)
{
    for (const auto& value : values) {
        validateEnumValues(value.second, allowedValues);
    }
}

template <typename Target>
struct JsonValueConverter
{
    static boost::json::value toJsonValue(const Target& sourceValue)
    {
        return boost::json::value_from(sourceValue);
    }

    static Target fromJsonValue(const boost::json::value& jsonValue)
    {
        return boost::json::value_to<Target>(jsonValue);
    }
};

template <>
struct JsonValueConverter<std::nullptr_t>
{
    static boost::json::value toJsonValue(std::nullptr_t)
    {
        return nullptr;
    }

    static std::nullptr_t fromJsonValue(const boost::json::value& jsonValue)
    {
        if (!jsonValue.is_null()) {
            throw std::invalid_argument("Expected a null JSON value");
        }
        return nullptr;
    }
};

template <typename ModelType>
struct JsonValueConverter<std::shared_ptr<ModelType>>
{
    static boost::json::value toJsonValue(const std::shared_ptr<ModelType>& model)
    {
        return model == nullptr ? boost::json::value(nullptr) : model->toJsonValue();
    }

    static std::shared_ptr<ModelType> fromJsonValue(const boost::json::value& jsonValue)
    {
        if (jsonValue.is_null()) {
            return nullptr;
        }
        return std::make_shared<ModelType>(jsonValue);
    }
};

template <typename Element>
struct JsonValueConverter<std::vector<Element>>
{
    static boost::json::value toJsonValue(const std::vector<Element>& sourceValues)
    {
        boost::json::array jsonValues;
        for (const auto& sourceValue : sourceValues) {
            jsonValues.emplace_back(JsonValueConverter<Element>::toJsonValue(sourceValue));
        }
        return jsonValues;
    }

    static std::vector<Element> fromJsonValue(const boost::json::value& jsonValue)
    {
        const auto& jsonValues = jsonValue.as_array();
        std::vector<Element> convertedValues;
        convertedValues.reserve(jsonValues.size());
        for (const auto& jsonElement : jsonValues) {
            convertedValues.emplace_back(JsonValueConverter<Element>::fromJsonValue(jsonElement));
        }
        return convertedValues;
    }
};

template <typename MappedValue>
struct JsonValueConverter<std::map<std::string, MappedValue>>
{
    static boost::json::value toJsonValue(const std::map<std::string, MappedValue>& sourceValues)
    {
        boost::json::object jsonValues;
        for (const auto& sourceEntry : sourceValues) {
            jsonValues[sourceEntry.first] = JsonValueConverter<MappedValue>::toJsonValue(sourceEntry.second);
        }
        return jsonValues;
    }

    static std::map<std::string, MappedValue> fromJsonValue(const boost::json::value& jsonValue)
    {
        std::map<std::string, MappedValue> convertedValues;
        for (const auto& jsonEntry : jsonValue.as_object()) {
            const std::string entryKey(jsonEntry.key().data(), jsonEntry.key().size());
            convertedValues.emplace(entryKey, JsonValueConverter<MappedValue>::fromJsonValue(jsonEntry.value()));
        }
        return convertedValues;
    }
};

void writePrettyJson(std::ostream& output, boost::json::value const& value, std::string& indent)
{
    if (value.is_object()) {
        const auto& object = value.as_object();
        if (object.empty()) {
            output << "{}";
            return;
        }

        output << "{\n";
        indent.append(4, ' ');
        for (auto iterator = object.begin(); iterator != object.end(); ++iterator) {
            output << indent << boost::json::serialize(iterator->key()) << ": ";
            writePrettyJson(output, iterator->value(), indent);
            if (std::next(iterator) != object.end()) {
                output << ',';
            }
            output << '\n';
        }
        indent.resize(indent.size() - 4);
        output << indent << '}';
        return;
    }

    if (value.is_array()) {
        const auto& array = value.as_array();
        if (array.empty()) {
            output << "[]";
            return;
        }

        output << "[\n";
        indent.append(4, ' ');
        for (auto iterator = array.begin(); iterator != array.end(); ++iterator) {
            output << indent;
            writePrettyJson(output, *iterator, indent);
            if (std::next(iterator) != array.end()) {
                output << ',';
            }
            output << '\n';
        }
        indent.resize(indent.size() - 4);
        output << indent << ']';
        return;
    }

    output << boost::json::serialize(value);
}
}

DnsRecord::DnsRecord(boost::json::value const& value)
{
    fromJsonValue(value);
}

std::string DnsRecord::toJsonString(bool prettyJson /* = false */) const
{
    const auto value = toJsonValue();
    if (!prettyJson) {
        return boost::json::serialize(value);
    }

    std::ostringstream output;
    std::string indent;
    writePrettyJson(output, value, indent);
    return output.str();
}

void DnsRecord::fromJsonString(std::string const& jsonString)
{
    fromJsonValue(boost::json::parse(jsonString));
}

boost::json::value DnsRecord::toJsonValue() const
{
    return boost::json::value(toJsonObject_internal());
}

void DnsRecord::fromJsonValue(boost::json::value const& value)
{
    if (!value.is_object()) {
        throw std::invalid_argument("Expected a JSON object for DnsRecord");
    }
    fromJsonObject_internal(value.as_object());
}

boost::json::object DnsRecord::toJsonObject_internal() const
{
    boost::json::object object;
        object["id"] = JsonValueConverter<std::string>::toJsonValue(getId());
        object["domain_id"] = JsonValueConverter<std::string>::toJsonValue(getDomainId());
        object["name"] = JsonValueConverter<std::string>::toJsonValue(getName());
        object["type"] = JsonValueConverter<std::shared_ptr<DnsRecordType>>::toJsonValue(getType());
        object["content"] = JsonValueConverter<std::string>::toJsonValue(getContent());
        object["ttl"] = JsonValueConverter<std::string>::toJsonValue(getTtl());
        object["prio"] = JsonValueConverter<std::string>::toJsonValue(getPrio());
        object["disabled"] = JsonValueConverter<std::string>::toJsonValue(getDisabled());
        object["ordername"] = JsonValueConverter<std::string>::toJsonValue(getOrdername());
        object["auth"] = JsonValueConverter<std::string>::toJsonValue(getAuth());
    return object;
}

void DnsRecord::fromJsonObject_internal(boost::json::object const& object)
{
    {
        const auto IdIt = object.find("id");
        if (IdIt != object.end()) {
            setId(JsonValueConverter<std::string>::fromJsonValue(IdIt->value()));
        }
    }
    {
        const auto Domain_idIt = object.find("domain_id");
        if (Domain_idIt != object.end()) {
            setDomainId(JsonValueConverter<std::string>::fromJsonValue(Domain_idIt->value()));
        }
    }
    {
        const auto NameIt = object.find("name");
        if (NameIt != object.end()) {
            setName(JsonValueConverter<std::string>::fromJsonValue(NameIt->value()));
        }
    }
    {
        const auto TypeIt = object.find("type");
        if (TypeIt != object.end()) {
            setType(JsonValueConverter<std::shared_ptr<DnsRecordType>>::fromJsonValue(TypeIt->value()));
        }
    }
    {
        const auto ContentIt = object.find("content");
        if (ContentIt != object.end()) {
            setContent(JsonValueConverter<std::string>::fromJsonValue(ContentIt->value()));
        }
    }
    {
        const auto TtlIt = object.find("ttl");
        if (TtlIt != object.end()) {
            setTtl(JsonValueConverter<std::string>::fromJsonValue(TtlIt->value()));
        }
    }
    {
        const auto PrioIt = object.find("prio");
        if (PrioIt != object.end()) {
            setPrio(JsonValueConverter<std::string>::fromJsonValue(PrioIt->value()));
        }
    }
    {
        const auto DisabledIt = object.find("disabled");
        if (DisabledIt != object.end()) {
            setDisabled(JsonValueConverter<std::string>::fromJsonValue(DisabledIt->value()));
        }
    }
    {
        const auto OrdernameIt = object.find("ordername");
        if (OrdernameIt != object.end()) {
            setOrdername(JsonValueConverter<std::string>::fromJsonValue(OrdernameIt->value()));
        }
    }
    {
        const auto AuthIt = object.find("auth");
        if (AuthIt != object.end()) {
            setAuth(JsonValueConverter<std::string>::fromJsonValue(AuthIt->value()));
        }
    }
}

std::string DnsRecord::getId() const
{
    return m_Id;
}

void DnsRecord::setId(std::string value)
{
    
    m_Id = std::move(value);
}
std::string DnsRecord::getDomainId() const
{
    return m_Domain_id;
}

void DnsRecord::setDomainId(std::string value)
{
    
    m_Domain_id = std::move(value);
}
std::string DnsRecord::getName() const
{
    return m_Name;
}

void DnsRecord::setName(std::string value)
{
    
    m_Name = std::move(value);
}
std::shared_ptr<DnsRecordType> DnsRecord::getType() const
{
    return m_Type;
}

void DnsRecord::setType(std::shared_ptr<DnsRecordType> value)
{
    
    m_Type = std::move(value);
}
std::string DnsRecord::getContent() const
{
    return m_Content;
}

void DnsRecord::setContent(std::string value)
{
    
    m_Content = std::move(value);
}
std::string DnsRecord::getTtl() const
{
    return m_Ttl;
}

void DnsRecord::setTtl(std::string value)
{
    
    m_Ttl = std::move(value);
}
std::string DnsRecord::getPrio() const
{
    return m_Prio;
}

void DnsRecord::setPrio(std::string value)
{
    
    m_Prio = std::move(value);
}
std::string DnsRecord::getDisabled() const
{
    return m_Disabled;
}

void DnsRecord::setDisabled(std::string value)
{
    
    m_Disabled = std::move(value);
}
std::string DnsRecord::getOrdername() const
{
    return m_Ordername;
}

void DnsRecord::setOrdername(std::string value)
{
    
    m_Ordername = std::move(value);
}
std::string DnsRecord::getAuth() const
{
    return m_Auth;
}

void DnsRecord::setAuth(std::string value)
{
    
    m_Auth = std::move(value);
}

std::string createJsonStringFromModelVector(const std::vector<std::shared_ptr<DnsRecord>>& data)
{
    return boost::json::serialize(JsonValueConverter<std::vector<std::shared_ptr<DnsRecord>>>::toJsonValue(data));
}

void createModelVectorFromJsonString(std::vector<std::shared_ptr<DnsRecord>>& vec, const std::string& json)
{
    vec = JsonValueConverter<std::vector<std::shared_ptr<DnsRecord>>>::fromJsonValue(boost::json::parse(json));
}

}
}
}
}

