/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "DomainDnssecRecords_inner.h"

#include <cstddef>
#include <map>
#include <memory>
#include <stdexcept>
#include <sstream>
#include <string>
#include <iterator>
#include <utility>
#include <vector>
#include <boost/json.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace {

template <typename Target>
struct JsonValueConverter
{
    static boost::json::value toJsonValue(const Target& sourceValue)
    {
        return boost::json::value_from(sourceValue);
    }

    static Target fromJsonValue(const boost::json::value& jsonValue)
    {
        return boost::json::value_to<Target>(jsonValue);
    }
};

template <>
struct JsonValueConverter<std::nullptr_t>
{
    static boost::json::value toJsonValue(std::nullptr_t)
    {
        return nullptr;
    }

    static std::nullptr_t fromJsonValue(const boost::json::value& jsonValue)
    {
        if (!jsonValue.is_null()) {
            throw std::invalid_argument("Expected a null JSON value");
        }
        return nullptr;
    }
};

template <typename ModelType>
struct JsonValueConverter<std::shared_ptr<ModelType>>
{
    static boost::json::value toJsonValue(const std::shared_ptr<ModelType>& model)
    {
        return model == nullptr ? boost::json::value(nullptr) : model->toJsonValue();
    }

    static std::shared_ptr<ModelType> fromJsonValue(const boost::json::value& jsonValue)
    {
        if (jsonValue.is_null()) {
            return nullptr;
        }
        return std::make_shared<ModelType>(jsonValue);
    }
};

template <typename Element>
struct JsonValueConverter<std::vector<Element>>
{
    static boost::json::value toJsonValue(const std::vector<Element>& sourceValues)
    {
        boost::json::array jsonValues;
        for (const auto& sourceValue : sourceValues) {
            jsonValues.emplace_back(JsonValueConverter<Element>::toJsonValue(sourceValue));
        }
        return jsonValues;
    }

    static std::vector<Element> fromJsonValue(const boost::json::value& jsonValue)
    {
        const auto& jsonValues = jsonValue.as_array();
        std::vector<Element> convertedValues;
        convertedValues.reserve(jsonValues.size());
        for (const auto& jsonElement : jsonValues) {
            convertedValues.emplace_back(JsonValueConverter<Element>::fromJsonValue(jsonElement));
        }
        return convertedValues;
    }
};

template <typename MappedValue>
struct JsonValueConverter<std::map<std::string, MappedValue>>
{
    static boost::json::value toJsonValue(const std::map<std::string, MappedValue>& sourceValues)
    {
        boost::json::object jsonValues;
        for (const auto& sourceEntry : sourceValues) {
            jsonValues[sourceEntry.first] = JsonValueConverter<MappedValue>::toJsonValue(sourceEntry.second);
        }
        return jsonValues;
    }

    static std::map<std::string, MappedValue> fromJsonValue(const boost::json::value& jsonValue)
    {
        std::map<std::string, MappedValue> convertedValues;
        for (const auto& jsonEntry : jsonValue.as_object()) {
            const std::string entryKey(jsonEntry.key().data(), jsonEntry.key().size());
            convertedValues.emplace(entryKey, JsonValueConverter<MappedValue>::fromJsonValue(jsonEntry.value()));
        }
        return convertedValues;
    }
};

void writePrettyJson(std::ostream& output, boost::json::value const& value, std::string& indent)
{
    if (value.is_object()) {
        const auto& object = value.as_object();
        if (object.empty()) {
            output << "{}";
            return;
        }

        output << "{\n";
        indent.append(4, ' ');
        for (auto iterator = object.begin(); iterator != object.end(); ++iterator) {
            output << indent << boost::json::serialize(iterator->key()) << ": ";
            writePrettyJson(output, iterator->value(), indent);
            if (std::next(iterator) != object.end()) {
                output << ',';
            }
            output << '\n';
        }
        indent.resize(indent.size() - 4);
        output << indent << '}';
        return;
    }

    if (value.is_array()) {
        const auto& array = value.as_array();
        if (array.empty()) {
            output << "[]";
            return;
        }

        output << "[\n";
        indent.append(4, ' ');
        for (auto iterator = array.begin(); iterator != array.end(); ++iterator) {
            output << indent;
            writePrettyJson(output, *iterator, indent);
            if (std::next(iterator) != array.end()) {
                output << ',';
            }
            output << '\n';
        }
        indent.resize(indent.size() - 4);
        output << indent << ']';
        return;
    }

    output << boost::json::serialize(value);
}
}

DomainDnssecRecords_inner::DomainDnssecRecords_inner(boost::json::value const& value)
{
    fromJsonValue(value);
}

std::string DomainDnssecRecords_inner::toJsonString(bool prettyJson /* = false */) const
{
    const auto value = toJsonValue();
    if (!prettyJson) {
        return boost::json::serialize(value);
    }

    std::ostringstream output;
    std::string indent;
    writePrettyJson(output, value, indent);
    return output.str();
}

void DomainDnssecRecords_inner::fromJsonString(std::string const& jsonString)
{
    fromJsonValue(boost::json::parse(jsonString));
}

boost::json::value DomainDnssecRecords_inner::toJsonValue() const
{
    return boost::json::value(toJsonObject_internal());
}

void DomainDnssecRecords_inner::fromJsonValue(boost::json::value const& value)
{
    if (!value.is_object()) {
        throw std::invalid_argument("Expected a JSON object for DomainDnssecRecords_inner");
    }
    fromJsonObject_internal(value.as_object());
}

boost::json::object DomainDnssecRecords_inner::toJsonObject_internal() const
{
    boost::json::object object;
        if (m_AlgorithmIsSet) {
            object["algorithm"] = JsonValueConverter<std::string>::toJsonValue(getAlgorithm());
        }
        if (m_Digest_typeIsSet) {
            object["digest_type"] = JsonValueConverter<std::string>::toJsonValue(getDigestType());
        }
        if (m_DigestIsSet) {
            object["digest"] = JsonValueConverter<std::string>::toJsonValue(getDigest());
        }
        if (m_Key_tagIsSet) {
            object["key_tag"] = JsonValueConverter<std::string>::toJsonValue(getKeyTag());
        }
    return object;
}

void DomainDnssecRecords_inner::fromJsonObject_internal(boost::json::object const& object)
{
    m_AlgorithmIsSet = false;
    m_Digest_typeIsSet = false;
    m_DigestIsSet = false;
    m_Key_tagIsSet = false;
    {
        const auto AlgorithmIt = object.find("algorithm");
        if (AlgorithmIt != object.end()) {
            setAlgorithm(JsonValueConverter<std::string>::fromJsonValue(AlgorithmIt->value()));
        }
    }
    {
        const auto Digest_typeIt = object.find("digest_type");
        if (Digest_typeIt != object.end()) {
            setDigestType(JsonValueConverter<std::string>::fromJsonValue(Digest_typeIt->value()));
        }
    }
    {
        const auto DigestIt = object.find("digest");
        if (DigestIt != object.end()) {
            setDigest(JsonValueConverter<std::string>::fromJsonValue(DigestIt->value()));
        }
    }
    {
        const auto Key_tagIt = object.find("key_tag");
        if (Key_tagIt != object.end()) {
            setKeyTag(JsonValueConverter<std::string>::fromJsonValue(Key_tagIt->value()));
        }
    }
}

std::string DomainDnssecRecords_inner::getAlgorithm() const
{
    return m_Algorithm;
}

void DomainDnssecRecords_inner::setAlgorithm(std::string value)
{
    
    m_Algorithm = std::move(value);
    m_AlgorithmIsSet = true;
}
std::string DomainDnssecRecords_inner::getDigestType() const
{
    return m_Digest_type;
}

void DomainDnssecRecords_inner::setDigestType(std::string value)
{
    
    m_Digest_type = std::move(value);
    m_Digest_typeIsSet = true;
}
std::string DomainDnssecRecords_inner::getDigest() const
{
    return m_Digest;
}

void DomainDnssecRecords_inner::setDigest(std::string value)
{
    
    m_Digest = std::move(value);
    m_DigestIsSet = true;
}
std::string DomainDnssecRecords_inner::getKeyTag() const
{
    return m_Key_tag;
}

void DomainDnssecRecords_inner::setKeyTag(std::string value)
{
    
    m_Key_tag = std::move(value);
    m_Key_tagIsSet = true;
}

std::string createJsonStringFromModelVector(const std::vector<std::shared_ptr<DomainDnssecRecords_inner>>& data)
{
    return boost::json::serialize(JsonValueConverter<std::vector<std::shared_ptr<DomainDnssecRecords_inner>>>::toJsonValue(data));
}

void createModelVectorFromJsonString(std::vector<std::shared_ptr<DomainDnssecRecords_inner>>& vec, const std::string& json)
{
    vec = JsonValueConverter<std::vector<std::shared_ptr<DomainDnssecRecords_inner>>>::fromJsonValue(boost::json::parse(json));
}

}
}
}
}

