/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * HomeDetailsModulesServers.h
 *
 * Dashboard module configuration for dedicated server services.
 */

#ifndef BOOST_BEAST_OPENAPI_CLIENT_HomeDetailsModulesServers_MODEL_H_
#define BOOST_BEAST_OPENAPI_CLIENT_HomeDetailsModulesServers_MODEL_H_

#include <string>
#include <vector>
#include <memory>
#include <boost/json.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Dashboard module configuration for dedicated server services.
/// </summary>
class  HomeDetailsModulesServers
{
public:
    HomeDetailsModulesServers() = default;
    explicit HomeDetailsModulesServers(boost::json::value const& value);
    virtual ~HomeDetailsModulesServers() = default;

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::json::value toJsonValue() const;
    void fromJsonValue(boost::json::value const& value);

    /////////////////////////////////////////////
    /// HomeDetailsModulesServers members

    /// <summary>
    /// The icon for dedicated servers.
    /// </summary>
    std::string getIcon() const;
    void setIcon(std::string value);

    /// <summary>
    /// Link to view server.
    /// </summary>
    std::string getViewLink() const;
    void setViewLink(std::string value);

    /// <summary>
    /// Heading for dedicated servers.
    /// </summary>
    std::string getHeading() const;
    void setHeading(std::string value);

    /// <summary>
    /// Link to order server.
    /// </summary>
    std::string getBuyLink() const;
    void setBuyLink(std::string value);

    /// <summary>
    /// Link to view servers list.
    /// </summary>
    std::string getListLink() const;
    void setListLink(std::string value);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual boost::json::object toJsonObject_internal() const;
    virtual void fromJsonObject_internal(boost::json::object const& object);


protected:
    std::string m_Icon = "";
    bool m_IconIsSet = false;
    std::string m_View_link = "";
    bool m_View_linkIsSet = false;
    std::string m_Heading = "";
    bool m_HeadingIsSet = false;
    std::string m_Buy_link = "";
    bool m_Buy_linkIsSet = false;
    std::string m_List_link = "";
    bool m_List_linkIsSet = false;
};

std::string createJsonStringFromModelVector(const std::vector<std::shared_ptr<HomeDetailsModulesServers>>& data);

void createModelVectorFromJsonString(std::vector<std::shared_ptr<HomeDetailsModulesServers>>& vec, const std::string& json);

}
}
}
}


#endif /* BOOST_BEAST_OPENAPI_CLIENT_HomeDetailsModulesServers_MODEL_H_ */
