/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Home_services.h
 *
 * Users services.
 */

#ifndef BOOST_BEAST_OPENAPI_CLIENT_Home_services_MODEL_H_
#define BOOST_BEAST_OPENAPI_CLIENT_Home_services_MODEL_H_

#include "Home_services_backups.h"
#include "Home_services_servers.h"
#include "Home_services_domains.h"
#include "Home_services_licenses.h"
#include "Home_services_webhosting.h"
#include "Home_services_vps.h"
#include <vector>
#include <memory>
#include <boost/json.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Users services.
/// </summary>
class  Home_services
{
public:
    Home_services() = default;
    explicit Home_services(boost::json::value const& value);
    virtual ~Home_services() = default;

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::json::value toJsonValue() const;
    void fromJsonValue(boost::json::value const& value);

    /////////////////////////////////////////////
    /// Home_services members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_domains> getDomains() const;
    void setDomains(std::shared_ptr<Home_services_domains> value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_webhosting> getWebhosting() const;
    void setWebhosting(std::shared_ptr<Home_services_webhosting> value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_vps> getVps() const;
    void setVps(std::shared_ptr<Home_services_vps> value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_licenses> getLicenses() const;
    void setLicenses(std::shared_ptr<Home_services_licenses> value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_servers> getServers() const;
    void setServers(std::shared_ptr<Home_services_servers> value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Home_services_backups> getBackups() const;
    void setBackups(std::shared_ptr<Home_services_backups> value);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual boost::json::object toJsonObject_internal() const;
    virtual void fromJsonObject_internal(boost::json::object const& object);


protected:
    std::shared_ptr<Home_services_domains> m_Domains;
    bool m_DomainsIsSet = false;
    std::shared_ptr<Home_services_webhosting> m_Webhosting;
    bool m_WebhostingIsSet = false;
    std::shared_ptr<Home_services_vps> m_Vps;
    bool m_VpsIsSet = false;
    std::shared_ptr<Home_services_licenses> m_Licenses;
    bool m_LicensesIsSet = false;
    std::shared_ptr<Home_services_servers> m_Servers;
    bool m_ServersIsSet = false;
    std::shared_ptr<Home_services_backups> m_Backups;
    bool m_BackupsIsSet = false;
};

std::string createJsonStringFromModelVector(const std::vector<std::shared_ptr<Home_services>>& data);

void createModelVectorFromJsonString(std::vector<std::shared_ptr<Home_services>>& vec, const std::string& json);

}
}
}
}


#endif /* BOOST_BEAST_OPENAPI_CLIENT_Home_services_MODEL_H_ */
